### ISSUE TITLE
pluginstall command cant install what i declared between call  plug#begin() and call plug#end()

### ISSUE THREAD

**Issue by leeyunlong001230** [junegunn/vim-plug#1008]
as the title says, my plugInstall command not work,

![image](https://user-images.githubusercontent.com/41579966/91472475-15807780-e8ca-11ea-86cf-ce60ee9652dc.png)

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ x] Neovim

**Comment by leeyunlong001230** [comment]
is my vim-plug not rightly configured ?  sos

**Comment by mschilli87** [comment]
@leeyunlong001230: If you want others to help, I suggest making it easy for them.
If I want to test if your configuration works on my system, I need to manually type it out becaus instead of copy/pasting the text (which is the only relevant part), you shared only an image with a screenshot. :disappointed:

**Comment by leeyunlong001230** [comment]
> @leeyunlong001230: If you want others to help, I suggest making it easy for them.
> If I want to test if your configuration works on my system, I need to manually type it out becaus instead of copy/pasting the text (which is the only relevant part), you shared only an image with a screenshot. 😞

3q,i've found the cause.i have two plug segments,one in init.vim another in .vimrc,but the vimrc is less than the init.vim,and the vimrc loaded behind init.vim,I guess it's the key.thank you anyway

**Comment by mschilli87** [comment]
@leeyunlong001230: Please take a moment to recognize that nobody could have helped you with this problem based on the information you provided, but over 1000 emails were sent regarding this issue.
For the future, I highly recommend to get a fresh (minimal) install of your OS and the involved tools in a VM and try to reproduce your issue there. This will either lead you to the solution without asking anyone for help (likely in this case), or you will know what to include in the issue so others have a chance of helping (in this case, you would have had to include both config files and someone could have pointed out that the second plug section won't take effect due to the first).
