### ISSUE TITLE
How should I manage plugins across two .vim files?

### ISSUE THREAD

**Issue by chrisshroba** [junegunn/vim-plug#1016]
I currently have one vimrc which I check into source control and distribute to all machines I use, and I source a `~/.vimrc-local` at the end if it exists, for any machine-specific settings.

If I have machine-specific plugins to include, is there any way to specify them using my current setup (in `~/.vimrc-local`), or do I need to create a third file (.vim-plugins-local) which is sourced from within the  `plug#begin`/`plug#end` block, as #425 implies? I understand that I can't have a second `plug#begin`/`plug#end` block, so I'm wondering if there are any other solutions.

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by mschilli87** [comment]
The only alternative I see to having at least one more files specifiying the plugins would be to define you own syntax to include the global plugin lines as comments in one file and use some vimscript to read that file when processing the other, cut out the corresponding comments, uncomment, and source them. But personally I would probably just have the `plug#begin`/`plug#end` block in  `~/.vimrc-local` and source  `~/.vim_plug` and `~/.vim_plug-local` there specifiying the global and local plugins instead of that way more hacky two-file version.

**Comment by junegunn** [comment]
No, only single block is allowed.

>  I source a ~/.vimrc-local at the end if it exists, for any machine-specific settings.

You can just source the file from within begin-end block. If you have some settings and code that should be delayed until the end, you can put it in a function and make it triggered on VimEnter autocmd, or manually call it at the end of the file. I know this is not ideal, but I don't want to complicate things.

```vim
Plug 'junegunn/seoul256.vim'

function! Delayed()
  silent! colo seoul256
endfunction

autocmd VimEnter * call Delayed()
```

* `plug#begin` resets the internal data structures. If `plug#begin` doesn't reset the data, there will be duplicate entries when you reload your Vim configuration file, and vim-plug will have to deduplicate the list. Extra code required.
* `plug#end` does the heavy-lifting of initializing plugins. If we allow multiple plug blocks, `plug#end()` will be called multiple times, and it will do unnecessary work multiple times. Because vim-plug wouldn't know if this `plug#end()` is truly the last one. If we want to make things more efficient, we would need to replace `plug#end` with `plug#not_really_end` and manually call `plug#really_end` at the end.

**Comment by cheater** [comment]
Thanks for the info. It would be very useful if you could add this to the docs.
