### ISSUE TITLE
On-demand loading for <Plug> prefixed commands

### ISSUE THREAD

**Issue by obxhdx** [junegunn/vim-plug#107]
I'd like to configure [tpope/vim-commentary](https://github.com/tpope/vim-commentary) to be loaded when I hit the default `gc`/`gcc` mappings. But since these keys are mapped using `<Plug>` (e.g, `nmap gc  <Plug>Commentary`), I couldn't get it to work.

Here's what I tried:
- `Plug 'tpope/vim-commentary', { 'on': [ 'Commentary', 'CommentaryLine' ] }`
- `Plug 'tpope/vim-commentary', { 'on': [ '<Plug>Commentary', '<Plug>CommentaryLine' ] }`

The first only works if I type the `Commentary` command, instead of using the key mapping. The second doesn't work at all.

**Comment by hiberabyss** [comment]
@junegunn Is it possible specify keys to be pressed in `'for'` directly?
It will also be better if on demand loading by function name.

Thanks!

**Comment by junegunn** [comment]
@hiberabyss It's currently not possible, and I personally don't think it's a good idea to extend the option to cover more cases.

Because..

A properly implemented Vim plugin should already load lazily without any help from the plugin manager. On-demand loading should only be used as the last resort, it is basically a hacky workaround and is not guaranteed to work in every case. Adding more options will inadvertently suggest users to rely on them even when they don't need to.

Also, I'd like to stress that you should break down the startup time using `--startuptime` option before trying to optimize it any further. It is possible that you're over-engineering the problem and it will not give any noticeable benefit.

**Comment by hiberabyss** [comment]
@junegunn Got it, thanks for your suggestions!
