### ISSUE TITLE
On demand loading with user defined commands?

### ISSUE THREAD

**Issue by shmerl** [junegunn/vim-plug#1261]
I'm trying to load a few plugins based on a custom command. So I defined something like this:

```
" Command to trigger loading of debugging related plugins on-demand
command LoadDebug echo 'Loading debug plugins'
...
```

And then in the vim-plug section, I was doing this:

```
" DAP debugging support
Plug 'mfussenegger/nvim-dap', { 'on': 'LoadDebug' }
Plug 'rcarriga/nvim-dap-ui', { 'on': 'LoadDebug' }
```
But it doesn't work. It does work with some other commands defined by plugins themselves. Is there a way to make it work or may be I'm missing something?

- Type:
    - [✓] Bug
- OS:
    - [✓] Linux
- Vim:
    - [✓] Neovim

**Comment by wookayin** [comment]
vim-plug currently can't source lua plugins when lazy-loaded. #1157

**Comment by junegunn** [comment]
#1157 is now merged. Thanks @wookayin 

---

> Plug 'mfussenegger/nvim-dap', { 'on': 'LoadDebug' }


That's not how you do it. When you write `{ 'on': 'LoadDebug' }`, vim-plug defines a proxy command in that name which loads the plugin and executes the command from the plugin.

Instead, you can pass an empty array as `on` so that the plugins are not loaded, and call `plug#load` from your command to load those plugins later.

```vim
Plug 'mfussenegger/nvim-dap', { 'on': [] }
Plug 'rcarriga/nvim-dap-ui', { 'on': [] }

command! LoadDebug call plug#load('nvim-dap', 'nvim-dap-ui')
```
