### ISSUE TITLE
Demand loading on diff mode

### ISSUE THREAD

**Issue by jchain** [junegunn/vim-plug#142]
Can you make vim dynamically load a plugin on 'diff' mode?

Something like

    Plug 'vim-scripts/diffchar.vim' , { 'on' : 'diff' }

**Comment by vheon** [comment]
```viml
Plug 'diffchar.vim', { 'on': [] }
autocmd FileType diff call plug#load('diffchar.vim')
```

I think this would work as well.

**Comment by vheon** [comment]
```viml
Plug 'diffchar.vim', { 'on': [] }
autocmd FileType diff call plug#load('diffchar.vim')
```

If you don't specify the `user` in the `user/plugin` pattern it will default to `vim-script`.
I should work more or less but I'm not sure about the `diff` filetype.

**Comment by junegunn** [comment]
No, there's no native support for that, but you can write an autocmd like follows:

```vim
augroup load_plugin_on_diff
  autocmd!
  autocmd FilterWritePost * if &diff
    \| call plug#load('diffchar.vim') | autocmd! load_plugin_on_diff
    \| endif
augroup END
```

It should work, but that's just too much code for my taste. Ideally, we could tell the author of the plugin to move the most part of the code to autoload directory so that we don't need these tricks in the first place.

@vheon Thanks for the comment, but `diff` is not a type so the code won't work. And if it's a type, we can use `for` option, right? :)

**Comment by vheon** [comment]
@junegunn Oh, right :stuck_out_tongue_winking_eye:
