### ISSUE TITLE
Travis Spends Most Time Building Vim

### ISSUE THREAD

**Issue by starcraftman** [junegunn/vim-plug#176]
From recent build, the second one is the nox one that just installs a version of vim. Total is usually around 15 mins now. If we didn't build vm, would probably be like 3/4.
 93.1   4 min 34 sec    3 minutes ago   1.8.7   linux
93.2    1 min           7 minutes ago   1.9.2   linux
93.3    5 min 27 sec    2 minutes ago   1.9.3   linux
93.4    4 min 52 sec    3 minutes ago   2.0.0   linux

Build time for all cases except nox are lengthy not because of our project but because the initial hg clone is really long and the subsequent build is quite long too.

All we need to do is prebuild a compatible version of vim (with dynamic python/ruby) I guess. I mean it isn't like we absolutely always need to test the immediate latest vim tag. I might investigate this in a bit on a separate branch. 
- Zip/Extract onto machine
- Have some Ubuntu PPA with our own prebuild deb

**Comment by junegunn** [comment]
I know. It would be nice if we could cut down the time, but more important I think is that we make sure vim-plug works with various versions of Vim, which is the point that the current set of Travis CI builds is missing. I frequently have to work with the ancient RHEL 5 servers with Vim 7.0 at work, and vim-plug seems to work fine there. I wish such old versions of Vim are also tested on Travis CI.

**Comment by starcraftman** [comment]
@junegunn Right, too bad travis doesn't seem to be looking at that so far. Only thing I see is OSX on horizon. Currently might have ruby support, but python non functional > https://github.com/travis-ci/travis-ci/issues/2320

**Comment by starcraftman** [comment]
@junegunn Putting this on hold while I look at other stuff like recent bug.

I tried to create a deb & extract it from travis and that worked. Seem to have a small problem with vim runtimedir when reinstalled. Small error to solve. 

Alternatively, noticed that travis has arbitrary directory caching. http://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches

If we made our vim builds sit in some dir under home like $HOME/cache, we could then maybe cache them between builds & conditionally build if cache was empty.

**Comment by junegunn** [comment]
@starcraftman The page you linked says:

> The features described here are currently only available for private repositories on travis-ci.com and our new container-based infrastructure.

So it doesn't seem like an option. Anyway, thanks for looking into this.

**Comment by starcraftman** [comment]
@junegunn Damn, read a bit too quick. Guess they gotta make money somehow. Also seem to have extra dependency features for privates. 

Guess the debian thing I made probably only route.

**Comment by starcraftman** [comment]
@junegunn Update. I've created a rudimentary example on my branch [vim_deb2](https://github.com/starcraftman/vim-plug/tree/vim_deb2). Here the travis simply downloads a deb and installs. The build script & debs get managed on a separate git repo using an encrypted oauth. I didn't want to push debs into our main repo. See here https://github.com/plugvim/cache.

See speedup on this [travis build]( https://travis-ci.org/starcraftman/vim-plug/builds/51836619). About 1 minute for each.

Thoughts? I'm not a huge fan of using git for debs, I'm open to any other easy mechanism. I just used it because it was easy.

**Comment by starcraftman** [comment]
To be honest, I'm not even sure if I like this idea anymore. Funny since I brought it up. It adds complexity, and I don't think the current build time is a major impediment. I think this was more my own curiosity about what if I built a larger component based program on Travis. Shows a base method for test dependencies.

**Comment by junegunn** [comment]
@starcraftman Hmm, yeah, I agree. It would be of course nice if it's faster, but the current build time is not really the problem and I don't like having to maintain yet another repository just for testing vim-plug. Maybe there are other options, let's leave this issue open, and try to find a better solution as a long term goal.

**Comment by starcraftman** [comment]
@junegunn Agreed.

**Comment by zmughal** [comment]
You might be interested in what many Perl repos are doing this. They are pre-built versions of Perl set up so that any Perl-using project can test on many versions of Perl at once: <https://github.com/travis-perl/helpers>. Maybe you can make helpers so that any Vim project can do the same?

**Comment by starcraftman** [comment]
@zmughal I see, they kind of arrived at the same idea I did before me. So basically they just made an organization with scripts to keep these builds up to date with security fixes. It is out of scope of this project, but I might undertake it after the neovim patch. So you are suggesting I make something like Travis-Vim with prebuilt vim versions from latest 7.1-7.4, maybe even neovim snaps. Might be a neat little project.

**Comment by vheon** [comment]
> Might be a neat little project.
:+1:  I would gladly help If I knew a single thing about Travis :(

**Comment by starcraftman** [comment]
@vheon It isn't too hard, mainly just a linux environment with declarative syntax for languages you depend on. See our .travis.yml for example. Their documentation is pretty good, see http://docs.travis-ci.com/ . You can arbitrarily run any bash/scripting language to test/manipulate the env.

**Comment by rubik** [comment]
Cache is now available for public repos.

**Comment by starcraftman** [comment]
@rubik Yup, known this for a bit. I been a bit lazy on that. We don't issue many builds though as development has stabilized quite a bit.

I should make a PR for it, have leveraged it in my other projects.

**Comment by tweekmonster** [comment]
I was building Vim for my plugin's tests, and it took roughly [1m30s for a single job](https://travis-ci.org/tweekmonster/braceless.vim/builds/109773023) (65 of those seconds was spent building Vim).  It was annoying slow, so I created a Docker base image for testing Vim: https://github.com/tweekmonster/vim-testbed

It could be used to drastically cut down the time it takes to run CI.  The idea is that you build a container with the versions of Vim you need to test *once*, then use that in Travis CI.  I did this with my plugin and it cut the job time to about 30s: https://travis-ci.org/tweekmonster/braceless.vim/builds/110045243

This is the pre-built container I used for my tests, which has an extremely simple Dockerfile: https://github.com/tweekmonster/ubuntu-vims
It's not built with python or ruby, but a new image could be created easily with them prebuilt.  It looks like Travis-CI caches the images as well which means that the build times will be shorter after the image is initially pulled.

When I find some time today, I wouldn't mind submitting a PR.  But, since this solution requires a hosted container, it might be better for the prebuilt container to be hosted on @junegunn's own Docker Hub repo.

**Comment by starcraftman** [comment]
@tweekmonster I think we are generally happy enough with how short the build is now (about 2 mins). When this was first made, we used to always build and it was like 5+ per job.

At this time, we only build for one of the jobs (rest use the package version). We cache the build using travis cache.

**Comment by tweekmonster** [comment]
@starcraftman I guess I missed the part above about the cache...and the age of this issue.  I contacted @junegunn through email about the Docker images and he pointed me here.  The goal with vim-testbed is not just to improve the Travis-CI speed, but also allow for easy local testing with different builds of Vim.

FWIW here's the modifications required: https://github.com/junegunn/vim-plug/compare/master...tweekmonster:docker-tests

The script can still run like it used to locally without Docker, or with `docker run -it --rm -v $PWD:/testplugin tweekmonster/vim-plug vim-py`

Here's the Travis-CI build results from my branch: https://travis-ci.org/tweekmonster/vim-plug/builds/110246705

**Comment by junegunn** [comment]
@tweekmonster Although it's hard to say that the current test configuration impedes our development process, I'm in favor of the suggested approach as it seems easier to add more build targets and it allows local testing against different configurations. And it's faster, of course. Thanks for sharing the idea.

One thing I noticed while looking at the change you made is that it's not testing against different versions of Ruby. Is it possible?

**Comment by tweekmonster** [comment]
@junegunn I was looking into having the image build different versions of Python and Ruby, but RVM doesn't work in Alpine Linux.  I tried ruby-build as well, but a lot of the versions I tested failed to build.  

I went with Alpine because it's very small and I wasn't sure about Travis CI caching docker images.  But, since it does cache, I will probably use an Ubuntu base image which is larger, but better supported.

**Comment by tweekmonster** [comment]
Turns out I was incorrect in saying that Travis CI caches the docker images.  I must've misread the output saying that it was fetching a new version :sweat:  It's still not bad in terms of speed.

I made a version that's based on Debian that's able to build arbitrary versions of Vim with arbitrary versions of Python with PyEnv and Ruby with RVM.  The resulting container size is much larger than with Alpine, but the impact is ~10 extra seconds per build job.  The bulk of the time was spent building the image locally, which was about 17 minutes for 5 Vim versions.

Travis CI: https://travis-ci.org/tweekmonster/vim-plug/builds/110536649
Updated Dockerfile so you can see the versions: https://github.com/tweekmonster/vim-plug/blob/b316dcbc41ea4a1126e243fb77340c45f815e909/Dockerfile

**Comment by starcraftman** [comment]
@junegunn 
>  it seems easier to add more build targets 

Any target in particular we are missing that you want added? Main whole I see is Windows which we'd need AppVeyor for.

@tweekmonster Very interesting, big thanks for the continuing work. Too bad didn't have these speedy builds earlier when we were doing much more dev.

**Comment by junegunn** [comment]
@starcraftman 

> Any target in particular we are missing that you want added?

We're currently testing against the latest source (except vim-nox case), but wouldn't it be better if we also test using explicit version tags, like 7.0, 7.3, and 7.4 when Vim turns 7.5 in the future, the number of combinations will increase but that's what I'm thinking. Having said that, I think our coverage is already pretty good and fiddling with archaic 7.0 is probably a waste of time but the point is that it'll be easier to extend in the future.

**Comment by tweekmonster** [comment]
@starcraftman No problem at all.  vim-plug would be a great use case, but I'm working on this because unit testing Vim plugins is such a pain in the ass.  So if you have any input on vim-testbed regardless of its use in vim-plug, it would be much appreciated.

In other news, since you mentioned it I've been successful in getting the Vim win32 binary to run via wine in the container.  I've never used wine to run CUI programs, so I'm not getting the exact results I wanted.  Vader seems to run, but fails soon after since Vim seems to be confused about the $SHELL.  Wine clears the output before exiting, so nothing gets printed with `Vader!`.

![vim-plug](https://cloud.githubusercontent.com/assets/111942/13200745/14039114-d824-11e5-9e49-7c449288f4db.gif)

**Comment by starcraftman** [comment]
@tweekmonster I'm not sure testing against wine is the best route to go. Several issues, most importantly wine != Windows so even if vim-plug or someone else's plugin worked in wine it wouldn't guarantee it worked in Windows. Moreover, wine doesn't always work itself, hard to base tests on an unstable platform.  I'd say two choices present themselves.
- Make use of [AppVeyor](http://www.appveyor.com/), something we should probably look into on our own.
- Perhaps use one of MIcrosoft's own [VMs](https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/) . I would be happy just being able to specify testing against Windows 7.

**Comment by tweekmonster** [comment]
True enough about wine.  It's been a little too obtuse to even get running reliably just for vim-only features.

A Win7 VM is a great idea for local testing since it could run programs in compatibility mode if you really wanted to go that old.  The only problem I see with it is that it's not very portable at 3.5GB for the Win7+IE9 one.  A script would most likely be needed to setup the VM for testing to have environment consistency across workstations.

**Comment by dbarnett** [comment]
This is still very much the case for the vim-nightly build, just not a concern for any of the others, correct?
