### ISSUE TITLE
How to search for plugins

### ISSUE THREAD

**Issue by mayuroks** [junegunn/vim-plug#186]
I have been using Vundle for quite some time and it has functionality to search for plugins. I read the README fpr vim-plug but I am not sure how to search for plugins. Is there a command thats meant to do some thing like PlugSearch ?

**Comment by junegunn** [comment]
No, the feature has never been a consideration.

Vundle can only find the plugins that are published to vim.org and mirrored on https://github.com/vim-scripts. So you can just use your browser to search for plugins like Vundle from this page: https://github.com/vim-scripts?tab=repositories. However, note that the list is far from complete since a lot of recent vim plugins (including many of mine) are not even published to vim.org.

**Comment by starcraftman** [comment]
@mayuroks Apart from vim.org, until recently there wasn't a great way to find plugins. I recommend you go to http://vimawesome.com/ . It has a tagged collection of plugins that is searchable. 

@junegunn On a related note, vim awesome recently added vim-plug as a method to install alongside Vundle, NeoBundle & pathogen. Just fyi.

**Comment by junegunn** [comment]
@starcraftman Thanks!
