### ISSUE TITLE
Updating fails even with Python 2.6+ installed

### ISSUE THREAD

**Issue by cparadis6191** [junegunn/vim-plug#188]
I've been using vim-plug for a while with no problems but recently `:PlugUpdate` started to fail with

```bash
Updated. Elapsed time: 2.255018 sec.
[xx==]

- Finishing ... Done!
- vim-fugitive: Already up-to-date.
- rainbow_parentheses.vim: Already up-to-date.
x vimwiki
    [87;1H[?1l>[?12l[?25h[?1049lVim: Caught deadly signal SEGV
x syntastic
    [87;1H[m[?1l>[?12l[?25h[?1049lVim: Caught deadly signal SEGV
```

This happens on a default Cygwin install (with vim and git installed) with the default Python installation.

```bash
$ python --version
Python 2.7.8
```

```bash
$ vim --version
+python/dyn
+python3/dyn
+ruby/dyn
```

Installing Ruby fixes the problem and allows normal updating.

**Comment by junegunn** [comment]
Hmm, segmentation fault. This is probably due to the defect of the python interface of Vim you're running. Could you post the output of `:python import sys; print sys.version` from Vim?

/cc @starcraftman

**Comment by cparadis6191** [comment]
Sure thing. That gives

```bash
2.7.8 (default, Jul 28 2014, 01:34:03)
[GCC 4.8.3]
```

I'll try a different version of python sometime tomorrow when I get a chance and see if the problem persists.

**Comment by junegunn** [comment]
Thanks, I thought it was a similar problem to the one described [here](https://github.com/junegunn/vim-plug/wiki/faq#vim-caught-deadly-signal-segv). But the problem seems to be more complicated than I imagined.

> I've been using vim-plug for a while with no problems but recently :PlugUpdate started to fail 

Did vim-plug installer work in parallel back then? Or did it install plugins one by one?

**Comment by starcraftman** [comment]
@junegunn Interesting! Firstly, I hadn't really done any testing on cygwin, though I hadn't ruled out its use as it is technically posix, os.name reports posix under cygwin. So that's why he's using parallel even though I ruled out Windows support. 

I just ran a simple test with my own vimrc under Babun (a Cygwin wrapper) and found nicely that vim-plug install/update with python does indeed work under cygwin. Interrupting even works, though it is slow. Didn't see any issue. Though oddly, my GLog logger doesn't seem to work, odd since it is so simple. :(

@cparadis6191 Due to my above test, I think we have some local problem on your machine. When roughly was vim-plug working? When it did, was it working by installing 1 plugin at a time? Did you recently upgrade cygwin or a component of it manually or with setup? Have you installed new programs that changed your path? Are any of these programs superseding default cygwin ones, i.e. you had python in cygwin (at /usr/bin/python) then installed python 2.7.8 outside of cygwin & put it at front of path.

To provide me extra information, please report the output of the command `cygcheck.exe -c vim python`. Also, check where the programs are with: `which vim` & `which python`. Try the logger on your machine, though it might not work. In your ~/.vimrc add: ` let g:plug_log_on = 1 ` . Logs should appear in a folder at ~/plug_logs.

As a temporary fix, you can put in your `.vimrc` the following line to force the standard vimscript installer:
`let g:plug_threads = 1`

**Comment by junegunn** [comment]
@starcraftman He may have to uninstall Ruby or change the source a bit as ruby installer is taking precedence over python version.

**Comment by starcraftman** [comment]
@junegunn Ah yes, he did say that.

@cparadis6191 ensure you force python when you do the logging test. Either remove rubyfrom your path or edit `~/.vim/autoload/plug.vim` and set `let s:ruby = 0`

**Comment by starcraftman** [comment]
@junegunn Scratch my comment that python works. It does not, had ruby accidentally. 

I'll make a PR momentarily to disable on cygwin while I investigate.

**Comment by starcraftman** [comment]
@cparadis6191 To be clear, I still want your logs + other stuff mentioned. I'm not getting a segfault like you. Also, that usually happens at the beginning of the interpreter due to an incompatibility. In your case it was in the middle?

Main issue I currently see is control codes messing up the buffer window, that I'll look into.

**Comment by starcraftman** [comment]
@cparadis6191 Skip sending me logs, doubt they'd be different from mine. I'm curious to the output of cygcheck though for comparison sake. Also, can you give me the output of `uname -a` in cygwin shell.

**Comment by cparadis6191** [comment]
Sorry, I'm at work right now. I'll read through all this and respond in a few hours.

**Comment by starcraftman** [comment]
@cparadis6191 No problem, my initial comments were incorrect. Disregard the above, I was incorrect in my initial testing. Please just give me the output to the following two commands for now:
`uname -a` & `cygcheck.exe -c vim python`.

Due to the fact I can't reproduce this on real POSIX (i.e. Linux) this may be outside of this project as a cygwin bug. Though I may try to get some help from the cygwin mailing list.

**Comment by cparadis6191** [comment]
Here's the output of the latest thing you asked for.

```bash
$ uname -a
CYGWIN_NT-6.3-WOW msi-leopard 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
```

```bash
cygcheck -c vim python
Cygwin Package Information
Package              Version        Status
python               2.7.8-1        OK
vim                  7.4.629-1      OK
```

**Comment by cparadis6191** [comment]
> Did vim-plug installer work in parallel back then? Or did it install plugins one by one?

I seem to remember it working and doing things in parallel. I can try an older version of vim-plug to see if it acts the same. I tried setting it to do things one-by-one manually and it was very slow. I feel like I would've remember it being that slow.

**Comment by cparadis6191** [comment]
The latest [commit](https://github.com/junegunn/vim-plug/commit/b3226fbbf603145c7b464d0d3238dc5b1562a28a) avoids the problem but I can still help test for it.

**Comment by cparadis6191** [comment]
If I run a PlugUpdate after it errors out with the segv I get something like

```bash
Error detected while processing function <SNR>6_update..<SNR>6_update_impl..<SNR>6_git_version_requirement..<SN
R>6_system:
line    7:
E484: Can't open file /tmp/vgwYYi1/2
Error detected while processing function <SNR>6_update..<SNR>6_update_impl:
line   16:
E171: Missing :endif
```

Maybe this will help.

**Comment by junegunn** [comment]
@cparadis6191 Okay, I was trying to check if the problem was due to [the recent commit](https://github.com/junegunn/vim-plug/commit/3c6ac68947b63adbb07b97f7c7d20aab78123a7a) I made to the python installer. It's a trivial one, so it's unlikely, but I just wanted to make sure. Anyway, you confirmed that it's not the case and Python installer never worked properly on Cygwin. @starcraftman and I will try to find the workaround, but it's almost certainly because of the broken Vim distribution so I don't have high hopes.

**Comment by starcraftman** [comment]
@cparadis6191 That only seems to happen after the segv, so I assume it is a symptom of the poor state vim is left in post thread crash.

@junegunn What I know so far.
* The bug seems to be a race condition as when nthreads = 1 it never occurs in my testing. As nthreads increases so does probability as one would expect.
* I used traceback to see where the crash occurs and the trace is below. Line numbers in trace start at python << EOF line => line 0.
```vim
[PlugT-03,10:52:08.923845] syntastic: Dir /home/Jeremy/.vim/bundle/syntastic/
[PlugT-03,10:52:09.181860] TRACE: Trace:
Traceback (most recent call last):
  File "<string>", line 212, in manage
  File "<string>", line 252, in update
  File "<string>", line 280, in repo_uri
  File "<string>", line 137, in attempt_cmd
  File "<string>", line 189, in timeout_cmd
CmdFailed: ['', '\x1b[2;25H\x1b[38;5;135m8\x1b[m\x1b[38;5;252m\x1b[48;5;233m\x1b[3;13H\x1b[1m\x1b[38;5;161m\x1b[48;5;234m=                                    \x1b[m\x1b[38;5;252m\x1b[48;5;233m\x1b[38;5;81m\x1b[48;5;234m]\x1b[m\x1b[38;5;252m\x1b[48;5;233m\x1b[5;7H\x1b[38;5;229mtabular:\x1b[m\x1b[38;5;252m\x1b[48;5;233m Already installed       \x1b[6;7H\x1b[38;5;229mvim-lawrencium:\x1b[m\x1b[38;5;252m\x1b[48;5;233m Already installed\x1b[7;7H\x1b[38;5;229mDirDiff.vim:\x1b[m\x1b[38;5;252m\x1b[48;5;233m Already installed \x1b[8;7H\x1b[38;5;229mtaghighlight:\x1b[m\x1b[38;5;252m\x1b[48;5;233m Already installed\x1b[9;11H\x1b[38;5;229msleuth:\x1b[m\x1b[38;5;252m\x1b[48;5;233m Already installed\x1b[35;1H\x1b[39;49m\x1b[?1l\x1b>\x1b[?12l\x1b[?25h\x1b[?1049lVim: Caught deadly signal SEGV']
[PlugT-03,10:52:09.184860] x syntastic: 
[2;25H[38;5;135m8[m[38;5;252m[48;5;233m[3;13H[1m[38;5;161m[48;5;234m=                                    [m[38;5;252m[48;5;233m[38;5;81m[48;5;234m][m[38;5;252m[48;5;233m[5;7H[38;5;229mtabular:[m[38;5;252m[48;5;233m Already installed       [6;7H[38;5;229mvim-lawrencium:[m[38;5;252m[48;5;233m Already installed[7;7H[38;5;229mDirDiff.vim:[m[38;5;252m[48;5;233m Already installed [8;7H[38;5;229mtaghighlight:[m[38;5;252m[48;5;233m Already installed[9;11H[38;5;229msleuth:[m[38;5;252m[48;5;233m Already installed[35;1H[39;49m[?1l>[?12l[?25h[?1049lVim: Caught deadly signal SEGV
```
* Seems repo_uri fails with a bad return code & garbage collected from cmd output. The segv occurs I believe because as you can see there is a lot of control codes in the result buffer that then attempts to be put in the vim buffer which is not allowed. 

* I'm not actually sure why the repo_uri command fails, may try to run that outside of vim in parallel python threads. The command in question is: `cmd = 'git rev-parse --abbrev-ref HEAD 2>&1 && git config remote.origin.url'`. There shouldn't be any overlap since each thread operates on a separate dir.

**Comment by junegunn** [comment]
![plug-python-cygwin-errors](https://cloud.githubusercontent.com/assets/700826/6652940/512a194c-cac3-11e4-9391-009d7b088a4c.png)
Instead of SEGV, I'm getting silent errors as shown above. Just 1 or 2 errors when I do `:PlugInstall2`, but I can see many number of errors on `:PlugInstall8`. `g:plug_log_on` does not give additional info.

**Comment by starcraftman** [comment]
@junegunn Interesting in the difference but it doesn't quite shed light on the why we fail. Tracing python doesn't seem helpful, I was going to build a debug version of vim on cygwin but I couldn't even complete the hg checkout? Le sigh. Cygwin can be a pain.

```
Jeremy@Jeremy-PC% hg clone https://vim.googlecode.com/hg/ vim                                 [INS]
warning: vim.googlecode.com certificate with fingerprint 9c:df:52:b3:2a:2c:11:16:a1:c2:ba:78:66:ba:f6:84:31:0e:72:5d not verified (check hostfingerprints or web.cacerts config setting)
requesting all changes
adding changesets
adding manifests
adding file changes
added 6679 changesets with 32443 changes to 2772 files (+2 heads)
updating to branch default
      0 [main] python2.7 80752 child_info_fork::abort: address space needed by 'parsers.dll' (0x360000) is already occupied
abort: Resource temporarily unavailable
abort: Broken pipe
```

**Comment by junegunn** [comment]
@starcraftman Thanks for looking into it. Maybe we should stop trying. It's obvious that the problem is in Cygwin, not your code. Even if we somehow managed to find a way to circumvent these unclear issues, there's no guarantee that the fix is going to work on different (future) versions of Cygwin.

**Comment by starcraftman** [comment]
@junegunn I think I agree. I thought this might be a little thing but it is probably something to do with cygwin internals and how they build vim. Bit outside our scope. Also considering we now disable on Windows by default I guess there isn't much lost. I guess we can close. Too bad.
