### ISSUE TITLE
Error messages of PlugUpgrade with Python is not helpful

### ISSUE THREAD

**Issue by yous** [junegunn/vim-plug#200]
I have compiled my own Vim with user compiled Python 2.7, and when I do `:PlugUpgrade`, it says:
```
Error upgrading vim-plug: Vim(python):Traceback (most recent call last):
```

But I can't see the detailed error messages even if I call `:mess`. It just shows that 'traceback' line. I think the cause of this error of `:PlugUpgrade` is not related to this plugin, but it should give me detailed traceback.

**Comment by junegunn** [comment]
@starcraftman Can you look into this? Thanks.

**Comment by starcraftman** [comment]
@yous The code that does the upgrade is quite simple, sounds like a compilation/interpreter issue. I assume you are compiling because the local version of python is very old?

To make sure you actually used the new python version can you run this command inside vim:
`:python import platform; print platform.python_version()`. Does it match the system python version or the user compiled one? 

If it matches the system python, then you didn't compile vim with right interpreter. I'd suggest trying my build script on the [wiki](https://github.com/junegunn/vim-plug/wiki/python) .

If it does match the python version, something must be wrong with it. The code doing the plug upgrade is simple, you can test the user compiled python with this script:
```python
#!/usr/bin/env python
# encoding: utf-8
import urllib
import os
src = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
dst = os.path.expanduser('~/plug.vim')
urllib.urlretrieve(src, dst)
```

**Comment by starcraftman** [comment]
Oh and re the message usefulness, it is like the ruby version. We only print the v:exception object in the catch, and any tracing code we put in the interpreter code could fail before it logs to buffer (as seen previously with my GLog). I'd have to look at your local setup to see why it didn't actually show the traceback.

**Comment by yous** [comment]
`:python import platform; print platform.python_version()` gives me `2.7.9`. Vim is compiled with my custom Python, because the system has Python 2.5.

Actually, this problem is occurred in old machine. It has outdated `ca-certificates.crt` file in its system root, which leads a certificate error when retrieving `plug.vim` from GitHub through HTTPS. But this is not my actual problem. What I was saying in this issue is, I want the actual traceback of python script on `:PlugUpgrade`. If I haven't known this kind of issue of the machine, I can't get any clue from the error message. I want vim-plug to show multi-line error message if it has more than one line.

Sorry about the clearance of the my initial comment.

**Comment by starcraftman** [comment]
@yous Ah, I see so problem resolved you just want more verbose message. I do see your point, I wouldn't have looked at certs for quite a while......

I will see about this, I don't know why vim isn't printing trace. Does so in the other python block.

**Comment by junegunn** [comment]
@starcraftman @yous 
FYI, Ruby version of PlugUpgrade gives slightly better error messages like follows:
```
Error upgrading vim-plug: Vim(ruby):SocketError: getaddrinfo: nodename nor servname provided, or not known
Error upgrading vim-plug: Vim(ruby):OpenURI::HTTPError: 500 Domain Not Found
```
But the code never really gets a chance to run since most systems these days have curl installed. @yous How about wget? Is it also not available? Maybe we could also consider using wget when curl is not available. Just a passing thought.

**Comment by yous** [comment]
@junegunn wget is installed in the machine while curl is not. But this is a rare case, it runs Ubuntu 8.04.2.

**Comment by starcraftman** [comment]
@junegunn Aye, noticed that. The python interface doesn't print anything useful when __main__ throws an exception, seems like a bug with vim if_pyth.

As for adding wget, sounds good.

**Comment by junegunn** [comment]
@starcraftman Another idea that came to mind is to use `git`. We could `git clone --depth 1 vim-plug` on a temporary directory and just extract plug.vim from it. It's kind of a hassle, but git should always be available. So I think it makes sense.

**Comment by starcraftman** [comment]
@junegunn That actually is a very good idea, we could then simply have the curl primary & fall back to git? Or even just use git always.

**Comment by junegunn** [comment]
@starcraftman Yeah, we could then replace the current curl/ruby/python code with the one using git. I'll try to write one and make a PR.

**Comment by starcraftman** [comment]
@junegunn Sounds like plan.

**Comment by yous** [comment]
Nice! I like it.
