### ISSUE TITLE
Idea: use `gx` or similar mapping to jump to commit on Github

### ISSUE THREAD

**Issue by geoffharcourt** [junegunn/vim-plug#204]
I think Vundle used to show the URL of the commit, so you could use `gx` to jump to it and check out the comments or diff. This isn't a killer feature, but even if the only change was to output the repo URL under the plugin name (with no direct path to the commit) it would make checking out changes in greater detail easier.

**Comment by junegunn** [comment]
Thanks for the suggestion, I like the idea, but I want to keep vim-plug as simple as possible and do not want to bring in external assumptions (github url patterns) that we have no control over to the code base. Since all the relevant information is exposed as `g:plugs` variable, and the file type of vim-plug buffer is set to "vim-plug". We can write a "plugin" that extends vim-plug without touching the core. And I think it's how it should be done. I would gladly help the writers of such "plugins" by extending the API or adding User events if it's necessary.

**Comment by geoffharcourt** [comment]
Sounds good, thanks for the explanation.

**Comment by junegunn** [comment]
So here's a PoC implementation of gx which opens github commit url on the browser when on `:PlugDiff` screen. It uses `open` command that only works on OS X, and the code is far from ideal, but you get the idea.

```vim
function! s:plug_gx()
  let sha = matchstr(getline('.'), '^  \zs[0-9a-f]\{7}\ze ')
  if empty(sha)
    return
  endif
  let name = getline(search('^- .*:$', 'bn'))[2:-2]
  let uri = get(g:plugs[name], 'uri', '')
  if uri !~ 'github.com'
    return
  endif
  execute printf('silent !open https://github.com/%s/commit/%s',
          \ matchstr(uri, '\w*/'.name), sha)
  redraw!
endfunction

augroup PlugGx
  autocmd!
  autocmd FileType vim-plug nnoremap <buffer> <silent> gx :call <sid>plug_gx()<cr>
augroup END
```
