### ISSUE TITLE
does not work with ruby 2.1 and 2.2 (rvm)

### ISSUE THREAD

**Issue by korin** [junegunn/vim-plug#207]
https://travis-ci.org/korin/vim-plug
seems to be related to https://github.com/wayneeseguin/rvm/issues/3339

**Comment by junegunn** [comment]
Thanks for the heads up. It's more of an RVM issue, right? Vim [doesn't even start](https://travis-ci.org/korin/vim-plug/jobs/57456621#L1303), so there's nothing vim-plug can do to fix the problem.

**Comment by korin** [comment]
Yes and no. By default vim does not start so it is rvm/ruby issue but when I copied libruby.so* to /usr/lib/ vim starts. When I run PlugInstall etc then I get SEGV error so you can try reproduce.
Right now I have problem only with vim-plug and [vim-ctrlspace](https://github.com/szw/vim-ctrlspace).

**Comment by junegunn** [comment]
Ruby code cannot cause segmentation fault even if it wants to. It's almost certainly that the Ruby interface is not properly set (Simple `:ruby puts RUBY_VERSION` should fail), and it's not possible to circumvent the problem by changing the code in vim-plug (or vim-ctrlspace).

Having said that, I've confirmed that the problem can be fixed by setting LD_LIBRARY_PATH to `/usr/local/rvm/rubies/ruby-2.2.1` or by copying not just libruby* files but also `ruby` directory as a whole. You can see what's going on by examining the output of `strace`, and you'll notice that libruby will try to load ruby script files under `lib/ruby` directory.

**Comment by korin** [comment]
you are right

**Comment by mshiltonj** [comment]
I posted a comment about this on a related ticket. I did NOT have to copy files or change my LD_LIBRARY_PATH.  This may be a problem with the build scripts of vim, but I can't say for sure.

https://github.com/rvm/rvm/issues/3339#issuecomment-168434888
