### ISSUE TITLE
Delaying loading of UltiSnips for specific filetypes giving error

### ISSUE THREAD

**Issue by marlun** [junegunn/vim-plug#215]
If I add

```vim
Plug 'SirVer/ultisnips', { 'for': ['php', 'javascript'] }
```

I get the following error all the time when opening any file:

    Error detected while processing FileType Auto commands for "*":
    E117: Unknown function: UltiSnips#FileTypeChanged

I've seen some issues about YouCompleteMe doing a similar thing but havn't seen a recommended way of solving this for UltiSnips?

**Comment by junegunn** [comment]
If a plugin is declared with `for` option,  only `ftdetect` part of it is loaded. The `ftdetect` part of a plugin is responsible for setting the right type when a file is opened and it's usually very short and simple. For example, the entire `ftdetect` of rust.vim is only a single line:

```vim
au BufRead,BufNewFile *.rs set filetype=rust
```

It makes Vim see a file with `.rs` extension as a `rust` file. `set filetype` in turn triggers `FileType` event which notifies vim-plug to load the rest of the plugin. However, `ftdetect` of Ultisnips does more than that and calls one of its functions which is not yet loaded. So that's why you see the error. In short, the plugin is not designed to work well with on-demand loading feature of vim-plug.

We can look into the internals of the plugin and come up with a workaround like follows, which I think is super-ugly to be honest.

```vim
Plug 'SirVer/ultisnips', { 'for': [] }
augroup load_ultisnips
  autocmd!
  autocmd FileType php,javascript call plug#load('ultisnips')
        \| execute 'autocmd! load_ultisnips' | doautocmd FileType
augroup END
```

1. We avoid loading of the plugin by using empty `for` option. (empty `on` also works)
2. On `FileType` event for php or javascript, we load the plugin with `plug#load()` function
3. The loading should happen only once, so we clear the event handler with `autocmd!`
4. However, UltiSnips still doesn't work as its initialization is only triggered by `FileType`. It's already too late. So we manually trigger `FileType` with `doautocmd`.

Note that the workaround is built upon implementation details of UltiSnips which we generally shouldn't care about, and there's no guarantee that it will always work as expect.

**Comment by starcraftman** [comment]
@marlun I'm curious, are you doing this because you noticed a slowdown in --startuptime? Or is this a micro optimization that you just made because you've no need for snippets in other files? In the end, seems like ultisnips is simply setup to assume it is fully sourced.

**Comment by marlun** [comment]
@junegunn thanks for going through that again. @starcraftman it is a micro optimization just because I didn't need it in any other filetypes but I see thats it's very unnecessary unless I'm actually having any speed problems.
