### ISSUE TITLE
Request: ability to access git log on PlugUpgrade

### ISSUE THREAD

**Issue by fourjay** [junegunn/vim-plug#244]
It's just a request, but seems relatively simple, can you add a log function for PlugUpgrade somewhat corresponding to the "D" in the PlugUpdate/PlugStatus window.

**Comment by starcraftman** [comment]
@fourjay To clarify, you are asking for ability to get a log of the changes to vim-plug when PlugUpgrade happens right? Good question, currently we only download over the file. We could easily add a diff between old & new version. Not sure of an easy way of getting log diff without cloning repo.

**Comment by fourjay** [comment]
Yes, I'm looking for a log of changes to VimPlug itself when I do a PlugUpgrade.
I almost always glance at the logs after a PlugUpdate, as a guide to new features if nothing else. It makes some sense to do the same for vimPlug, in particular as it's seeing pretty active development :-)

**Comment by junegunn** [comment]
Thanks for the suggestion. But I'm afraid that it's not possible as vim-plug is distributed as a single downloadable file and not as a git repo as a whole. I'm not going to change that, you can see the discussion at #240. As @starcraftman mentioned, a simple diff would be possible on PlugUpgrade, but commit log is unavailable as we don't retain the history. If you really want to see the log somehow, you could manually clone the repo inside plugged directory and symlink plug.vim to your autoload directory and have it updated on PlugUpdate just like other plugins. But IMO I don't see the point of such hassle since vim-plug has been stable for some time and I'm very conservative on expanding its feature set.

**Comment by starcraftman** [comment]
@junegunn Just tossing it out there but we could use the [github api](https://api.github.com/repos/junegunn/vim-plug). If we kept a copy of the commits json on a user system, we could then just diff the old against new and pull off messages for the log to put in a pane. Trivial to fetch with python requests.

Problem with that:
1) Requires we store an extra file somewhere, perhaps opt-in with user setting a path in a global like g:plug_log_file.
2) 1 extra download per PlugUpgrade.

**Comment by junegunn** [comment]
@starcraftman I see, another problem is that it makes vim-plug dependent on github api, making it a little harder to migrate to bitbucket or somewhere when github explodes, just saying :) Or we could tell the users to reviews the changes on https://github.com/junegunn/vim-plug/releases and upgrade only when needed instead of blindly fetching the HEAD revision. vim-plug is not an ordinary plugin so it makes sense to be a bit more conservative on upgrade.

**Comment by starcraftman** [comment]
@junegunn Yes it would be a dependency, but not a very hard one since the function quite secondary to vim-plug's features. Won't actually require anything local, just an optional fetch long as api works.

Regarding moving to just releases, that has advantage of having predictable/releasable change log but might be a bit more conservative than we need be. I don't really see that need. 

I did a quick trivial implementation of possible PlugLog command just to illustrate. Fetches last 10 commits and puts in the pane. Could be made better with syn highlighting & better formatting. Not the most important feature I agree, just a thought I had during this thread.

```vim
function! s:github_log()
  call s:prepare()
python << EOF
import json
import requests
import vim

curbuf = vim.current.buffer
curbuf.append('vim-plug most recent commits')
del curbuf[0]
curbuf.append('----------------------------')
curbuf.append('')
req = requests.get('https://api.github.com/repos/junegunn/vim-plug/commits')
limit = 10
if req.ok:
  commits = json.loads(req.text or req.content)
  for obj in commits:
    sha = obj['sha'][0:8]
    msg = obj['commit']['message'].replace('\n', '\\n')
    date = obj['commit']['committer']['date']
    curbuf.append('{0} {1} {2}'.format(sha, msg, date))

    if limit == 0:                                                                                                
      break
    limit -= 1 
EOF
endfunction
```

**Comment by junegunn** [comment]
@starcraftman Thanks, but I don't like that it requires python. One alternative I can think of is to make a non-shallow (or partly-shallow) clone during PlugUpgrade and `git log --since $(stat mtime of current plug.vim)`.

**Comment by junegunn** [comment]
@starcraftman In either case, vim-plug still won't be able to show the diff from each commit like PlugDiff does and I'm not sure if I like such inconsistency. IMO, symlinking + PlugUpdate instead of PlugUpgrade is the most viable solution to the small number of users who would actually care about individual commits.

```sh
mkdir -p ~/.vim/{autoload,plugged}
git clone https://github.com/junegunn/vim-plug.git ~/.vim/plugged/
ln -s ~/.vim/plugged/vim-plug/plug.vim ~/.vim/autoload
```

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-plug'
...
```

The caveat is that you should **never** use PlugUpgrade.

**Comment by starcraftman** [comment]
@junegunn Fair enough, we can put it on the wiki somewhere I guess if that's how you want to resolve.

**Comment by junegunn** [comment]
@starcraftman Will do. Thanks for your constant contribution and input.

**Comment by starcraftman** [comment]
@junegunn No problem, I just try to pitch in when I can.
