### ISSUE TITLE
Neovim Possibly Including vim-plug

### ISSUE THREAD

**Issue by starcraftman** [junegunn/vim-plug#249]
Hi @junegunn you may want to read/weigh in at bottom of neovim/neovim#247 . They appear to be considering making vim-plug part of default. See fmorales comments.

Seems ok I guess. Though if they diverge and maintain naming, I can see some users being confused by differences. You can close this unless you want to have an offside discussion here. I guess it is mostly just something to monitor.

**Comment by junegunn** [comment]
Ah, thanks for letting me know. I think it's okay since users still can install a newer version of vim-plug in their `~/.vim/autoload` if they want to. But automatic invocation of `plug#begin()` and `plug#end()` seems like a bad idea.

- It's an unnecessary overhead if the user does not use vim-plug
- As you know, `&runtimepath` is not updated until `plug#end()` so it won't be
  possible to call autoload functions in .vimrc. The behavior is not something
  we can easily fix without paying the overhead of reassembling `&rtp` on
  every `Plug` command.

Oh, and they should also `:delcommand PlugUpgrade`.

/cc @fmoralesc

**Comment by fmoralesc** [comment]
Hi, @junegunn, thanks for taking a look. I did that just as a test of a way to provide a default plugin manager, there are no definitive plans. If this gained traction (which seems to be the case) I was going to contact you anyway to make sure we are in the clear. I used vim-plug mostly because of its simplicity and clean design, but the mechanism would be valid for any other plugin manager.

The idea here is to provide a default plugin managing system without further configuration, so it is important to give the user the ability to just use the `:Plug` commands in the nvimrc without the boilerplate of the `plug#...` functions. The overhead will be necessary. As to your second point, I hadn't considered it, although we can document this behavior and point users who get this issue to add the `plugin#end()` call themselves at an appropriate point in the vimrc.

Since the vim-plug plugin can be masked by user versions, perhaps we don't need to remove `:PlugUpgrade`.

**Comment by starcraftman** [comment]
@fmoralesc 
> The idea here is to provide a default plugin managing system without further configuration, so it is important to give the user the ability to just use the :Plug commands in the nvimrc without the boilerplate of the plug#... functions. 

I'm not sure I see why this is so critical, especially since vim-plug will require users to invoke plug#end (as noted above). Then you are only saving one plug#begin call and obfuscating part of the api.

A second thought is that if new users don't put `plug#begin()` in their vimrc and then try to use vim-plug on vim (correctly assuming a shared vimrc should basically work) they'll get a bunch of Command not found errors. Doesn't seem worth that hassle.

An alternative that comes to my mind is:
* Define either a manual or automatic bootstrap command and make it always available: Examples [vim-plug](https://github.com/junegunn/vim-plug/wiki/faq) or [my own](https://github.com/starcraftman/dot/blob/master/files/vimrc#L1063-L1107)
* Make a new doc page for plugin management (maybe `:h plugins`) where you explain to new users quickly how autoload & plugin layout works. Then quickly summarize what managers like vim-plug do & then point to the bootstrap command.

Hope I don`t sound too critical, I am happy you guys like vim-plug so much :)

**Comment by fmoralesc** [comment]
> I'm not sure I see why this is so critical, especially since vim-plug will require users to invoke plug#end (as noted above). Then you are only saving one plug#begin call and obfuscating part of the api.

The `plug#end()` call would be needed only if the user uses autoloaded functions in the vimrc, and I don't see that as the most common use case. Anyways, I'm thinking of proposing the early loading mechanism to vim_dev too, so vim-plug (or other plugin manager) can use this upstream if desired too. The idea is not to obfuscate the api, but instead make things simpler to users. The use of the `plug#begin()` and `plug#end()` calls are, imho, a crutch justified only because of the way vim has traditionally started. Every plugin manager does something like it out of necessity, but I feel we can do better than that. Even the need of calling `plug#end()` when the user uses an autoloaded function in the vimrc can be worked on. Again, the idea is to make the defining of plugins a 1st class feature of default (n)vim.

Bootstrapping is a good idea, it should certainly be a consideration. Also, documentation is sure to be needed.

> Hope I don`t sound too critical, I am happy you guys like vim-plug so much :)

No worries. You all have much more experience on the handling of plugin managers than I do, and I appreciate the discussion. Outside of high level talk about having vim and neovim provide a default plugin manager, this is (I believe) the first effort to make it for real, so the need to iron things out is expected. So don't think I'm defensive either ;); I just don't want this effort to be shot down before it takes flight.

**Comment by starcraftman** [comment]
@fmoralesc Well that's interesting, didn't imagine you were thinking of putting early changes into vim. We'll have to see if bram likes your proposal. Still, every vim version before such a merge wouldn't be able to take advantage. I guess it is nice as a convenience, but anyone needing to use older versions of vim couldn't take advantage of it.

**Comment by fmoralesc** [comment]
> I guess it is nice as a convenience, but anyone needing to use older versions of vim couldn't take advantage of it.

Yes, that is a downside.

**Comment by junegunn** [comment]
FYI.

The reason I [introduced `begin` ~ `end` block](https://github.com/junegunn/vim-plug/commit/09df71c3db7ca25cc6c7618a5c87555ffd483cf7) in the first place was not to require filetype off and on trick. I haven't checked if the workaround is still necessary, but I use vim-plug with Vim 7.0 when working on old RHEL5 servers at work so I'm not going to remove it.

And more importantly, explicit `end()` allows vim-plug to efficiently build `&rtp` while maintaining the order of plugins (~/.vim, plugins, after directories, ~/.vim/after). Reassembling `&rtp` on every `Plug` command should affect the startup time of Vim, though I haven't tried benchmarking it.

**Comment by fmoralesc** [comment]
I'm not suggesting removing the functions, the idea to make the whole setup transparent to the user where the mechanism I'm proposing is supported.

**Comment by junegunn** [comment]
> I'm not suggesting removing the functions

Yeah I know. Since nvim is based on much newer version of vim, `filetype off/on` may not be necessary. (not sure about that, see https://github.com/gmarik/Vundle.vim/issues/176) So the only issue left is the overhead of immediate `&rtp` update which may or may not matter. If it turns out to be quite small, we could add an option to vim-plug to enable immediate/incremental `&rtp` update which should allow smoother integration with nvim.

**Comment by fmoralesc** [comment]
>  Since nvim is based on much newer version of vim, filetype off/on may not be necessary.

I think it shouldn't be necessary, but I'll check. Besides, neovim might enable filetype detection and syntax by default in the future, see https://github.com/neovim/neovim/pull/2675.

**Comment by starcraftman** [comment]
@junegunn 
>  Reassembling &rtp on every Plug command should affect the startup time of Vim, though I haven't tried benchmarking it.

When I was contributing to Vundle we looked into that & brought in the same kind of delayed rtp changes as vim-plug. As I remember, there was a noticeable enough speedup when I tested. I don't think my testing was perfect though. Naturally, slower CPUs benefit most.

I'd leave api as is, I don't think many people care about the two autoload lines. People only care if their plugins install/work after starting up vim.

I can't comment on the filetype on/off issue, I'd just have to trust their investigation was correct.

**Comment by junegunn** [comment]
@starcraftman 
Agreed, I will not change the API. Vim is still my main editor, and I don't think it will change soon. And I presume many of the nvim users will still prefer to have a single .vimrc that can be used both for vim and nvim. Saving two lines in my opinion does not compensate for the confusion that might arise when they try to start vim with their .vimrc without those lines.

Having said that, I do see the benefit of immediate `&rtp` update since there are users (not me) who prefer to interleave their plugin settings with `Plug` declarations, and in that case delayed update does not work well with autoload functions and color schemes. We could simply say that they're doing it wrong, and there's a very obvious workaround to the problem (`autocmd VimEnter`), but **if** the overhead of immediate update is trivial, we could provide a flag or bang-version of `Plug` command which makes vim-plug eagerly update `&rtp`. But since you observed a noticeable overhead, we probably shouldn't as it would lead to suboptimal experience of vim-plug.

**Comment by pickfire** [comment]
Neovim now automatically execute `:filetype plugin indent on` and `:syntax on` now https://github.com/neovim/neovim/wiki/Following-HEAD#20160214

Should `vim-plug` still automatically execute `:filetype plugin indent on` now on neovim?

**Comment by junegunn** [comment]
@pickfire Looks like it doesn't have to. But not doing it will not give any noticeable benefit so I don't see a reason for vim-plug to proactively skip it.

**Comment by pickfire** [comment]
@junegunn Oh, thanks a lot for the plugin, it seems great and *fast*.
