### ISSUE TITLE
Per plug shallow configuration

### ISSUE THREAD

**Issue by vhda** [junegunn/vim-plug#251]
I like the idea of using shallow clones in the plugins, but I would like to have the possibility of having the full history of my plugins, or plugins I contribute to.
In this context it would make sense to have a configuration to override the global shallow setting.

What do you think?

**Comment by junegunn** [comment]
How about manually doing `git fetch --unshallow` once for those plugins? Or you could write `{ 'do': 'git fetch --unshallow; :' }`.
(See https://github.com/junegunn/vim-plug/issues/217#issuecomment-96372203)

**Comment by junegunn** [comment]
Or something like this, since it only has to be done once after the initial installation.
```vim
function! Unshallow(info)
  if a:info.status == 'installed' || a:info.force
    call system('git fetch --unshallow')
  endif
endfunction

Plug 'foo/bar', { 'do': function('Unshallow') }
```

**Comment by vhda** [comment]
Although not very user-friendly, the second solution is acceptable. I want to keep that configuration in my .vimrc, which I share among many computers and I may need the full history in any of them.
Would it be possible to at least document this in README.md for future reference to other people looking for the same feature?

Looking at https://github.com/junegunn/vim-plug/issues/217#issuecomment-96372203 it's a pity people didn't vote for option 7, which would please everyone.

**Comment by vhda** [comment]
If the function is so simple, why not include it in vim-plug and simply allow the following:
```
Plug '...' {'unshallow'}
```
or similar?

**Comment by junegunn** [comment]
Thanks for the suggestion. But I'd rather not because not too many people really need it (yes, you're the first one who has ever asked for this) and vim-plug tries to be as small as possible. With vim-plug, I've always been consciously conservative on including helper functions and options that are not completely necessary. They may seem harmless at the moment, but I believe in the long run they pile up and hurt the simplicity of the project.

**Comment by vhda** [comment]
Fair enough, especially since you provided an alternative route.

**Comment by vhda** [comment]
Could you please explain why the `; :` is necessary at the end of the command?

**Comment by junegunn** [comment]
Since `git fetch --unshallow` fails once the repository is "unshallowed" and vim-plug will warn you about it if not for that dummy command.

Also, consider this: the thing is, you don't need the entire history until you need to look at it. How often do you do that? I have written quite a few number of plugins myself, and I use them on many machines, but I rarely need to look at the commit history.

**Comment by vhda** [comment]
It's really one of those things that I don't want to be bothered with if I ever need it, specially since I may be without network access.
