### ISSUE TITLE
syntax enable in plugin

### ISSUE THREAD

**Issue by atommixz** [junegunn/vim-plug#274]
Your plugin setting syntax enable, but he should not do it if this disabled

**Comment by junegunn** [comment]
That's how vim-plug currently works. It enables syntax only during startup. So if you `syntax off` after `plug#end()`, it will not reenable it in any case.

**Comment by evesprini** [comment]
> That's how vim-plug currently works. It enables syntax only during startup. So if you `syntax off` after `plug#end()`, it will not reenable it in any case.

Still a bad idea. My `syntax off` odyssey:

I wanted to turn syntax highlighting off, but adding `syntax off` to my .vimrc didn't do anything. It took me like an hour to find out what the problem was.

Was some other setting overriding this? Debug time. My .vimrc was over 300 lines back then. Not efficient to comb through it all. Time to blindly do divide-and-conquer debugging: comment half of my .vimrc. Does the problem happen again? Yes? Okay, the problem is in the other half of the file. Comment half of that... recursively until I found that something in the plugin configuration was causing the problem.

It made sense in retrospect. Well, better get to work. Gotta do the same thing, for plugins now. Move the ones that can't possibly be causing the problem to the top, leaving something like 8 plugins left. Comment half of those and so on, all over again, but this time having to run `:PlugClean` every iteration. None of the plugins were causing the problem. Was I going insane? Maybe it was one of the other plugins I put at the top? Same process again. Again, none of the plugins were causing the problem. I really did feel like I was going insane.

I don't quite remember now, but eventually either deleting the whole vim-plug section or moving it to the top fixed it.
---
But sure, let's run `syntax on` for _convenience_!
![XKCD: goto](https://www.xkcd.com/292/)

Changing settings means that either the Plugins section must be at the top of the .vimrc or that other settings must be in the Plugins section instead of where they belong (for example, something like an UI section for `syntax on`). I understand `filetype plugin indent on` must stay for compatibility, but please consider removing setting `syntax on` so no one has to go through all that again. On modern Vim it's on by default anyway, and, unlike `filetype plugin indent on`, it won't cause problems that are hard to fix. Everyone running vim-plug knows how to turn highlighting on.

I know this will come off as overtly negative, so to fix that a bit: otherwise, vim-plug is an awesome Vim plugin solution and I'm thankful to you for making it.

**Comment by EvanCarroll** [comment]
see: #1083 Stop Turning `syntax on`
