### ISSUE TITLE
Problems when fetching a repository over http

### ISSUE THREAD

**Issue by LemonBoy** [junegunn/vim-plug#276]
When fetching a git repository such as [1] over http vim-plug chickens out with this error
``` fatal: dumb http transport does not support --depth ```

[1] http://git.foldling.org/vim-scheme.git

**Comment by starcraftman** [comment]
@LemonBoy Is this your own private website? The site in question doesn't have SSL support. It appears that using the `--depth` option requires SSL support on the remote. We started using `--depth 1` to reduce download size of the plugins. I don't think we'll be changing plug.vim because of this. 

Work arounds I can think of are:

1) Mirror this repository on github.com, on a public repository. No issue, as seems licensed under Public Domain. Then simply add it to your `~/.vimrc` as `Plug 'LemonBoy/vim-scheme'`.

2) Run this command to clone locally: `git clone http://git.foldling.org/vim-scheme.git ~/.vim/plugged/vim-scheme' Then add it to the `~/.vimrc` with the following line: `Plug '~/.vim/plugged/vim-scheme'`
By leading with a tilda, you indicate the plugin shouldn't be cloned/managed, just put on the rtp.

**Comment by junegunn** [comment]
> It appears that using the --depth option requires SSL support on the remote. 

Hmm, it's clearly something I wasn't aware of.

But anyway, you can put `let g:plug_shallow = 0` in your vimrc to disable shallow clone. It's a global option and currently it's not possible to disable it for a subset of plugins.

**Comment by LemonBoy** [comment]
Well, that's unfortunate, the shallow cloning is quite useful and disabling it globally is awful. Maybe you could add some code to detect the git-over-dumb-protocols urls and disable the shallow clone accordingly.
Anyway I'll just add it to the rtp manually for the time being.

**Comment by starcraftman** [comment]
@LemonBoy We could. Most servers have SSL support though, it is kind of a standard feature for authentication. Considering that, I think it is simplest to just document rather than add logic to the code. I've added a section to the FAQ, as I can see it happening more than once. Just not very often.

**Comment by junegunn** [comment]
@starcraftman Not that I want to. Most users don't have the problem and doing so will inevitably complicate the code. Testing it is also tricky.

**Comment by starcraftman** [comment]
@junegunn Agreed, closing this as won't fix. I think the documentation is enough.
