### ISSUE TITLE
Travis Build - Vim Fails To Compile

### ISSUE THREAD

**Issue by starcraftman** [junegunn/vim-plug#280]
I was messing around and found the travis build doesn't work since vim commit: 7e2ec00 (patch 7.4.855). You can see test builds on my travis, like this [one](https://travis-ci.org/starcraftman/vim-plug/jobs/79451710).

I think this may be a configure bug, since vim seems to think the travis environment has PANGO_SHAPE_FULL but upon linking it is undefined. See lines 622, 745-750.

We can fix the build by simply disabling gui entirely at configuration. I am going to make a PR momentarily.

**Comment by junegunn** [comment]
Ah, thanks. Hmm, maybe we should use a fixed revision instead of pulling the HEAD? What do you think? By doing so we'll have reproducible build, but we may not be able to deal with the issues/changes in the latest version, though such changes are not likely considering the conservative stance of Vim.

**Comment by starcraftman** [comment]
@junegunn Well, I kinda do want to know if something they put on the HEAD of vim breaks vim-plug. I think going with --disable-gui will be fine for now. I might even report this, as it does seem wrong. Unless Travis is doing something weird with gtk libs.

**Comment by junegunn** [comment]
@starcraftman Okay!
