### ISSUE TITLE
Clone branch pointed by origin/HEAD instead of 'master' by default

### ISSUE THREAD

**Issue by ABorgna** [junegunn/vim-plug#288]
Installing a plugin from github without specifying a branch makes vim-plug try to clone the 'master' branch. 
But the repository's default branch [can be changed](https://github.com/blog/421-pick-your-default-branch), and the installation fails if 'master' doesn't exist.

##### Steps to reproduce
* Add a [plugin](https://github.com/rdnetto/YCM-Generator) without a `master` branch in it's repo to `.vimrc`.
``` Plug 'rdnetto/YCM-Generator' ```

* Install it with `:PlugInstall`.

##### Output
```
- Finishing ... Done!
x YCM-Generator:
    error: pathspec 'master' did not match any file(s) known to git.
```

Explicitly setting the `branch` option in the plugin line solves the issue, but I think we should use the default branch (which is pointed by the origin's HEAD) if none specified.

**Comment by starcraftman** [comment]
@ABorgna Isn't that a catch 22 though? We are - during PlugInstall - directly cloning the exact branch requested (master by default) at `--depth 1` to reduce bandwidth/storage. How do we know the origin's HEAD ref before cloning? I know you can run `git symbolic-ref HEAD` post clone.

IMO rdnetto should just have a master branch, like literally every other plugin I've ever installed or seen. Seems silly breaking such a convention for no strong reason I can see.

**Comment by ABorgna** [comment]
I agree this is not a common issue, but `git clone` used without specifying a branch clones the default.
So maybe conditionally adding the `-b` option iff a branch or tag was explicitly set would fix it.

**Comment by starcraftman** [comment]
@ABorgna That is true, I think the reason we use the `-b` option is to prevent it cloning all branch information into `.git`. @junegunn would have to confirm, as I've forgotten if that was the case.

**Comment by ABorgna** [comment]
`-b` only sets the branch the local HEAD points to after the clone.
`clone_opt` has `--no-single-branch`, so every branch is being fetched ([here's](https://github.com/junegunn/vim-plug/issues/217#issuecomment-95945471) @junegunn comment about it).

**Comment by junegunn** [comment]
This was discussed before (https://github.com/junegunn/vim-plug/issues/257#issuecomment-121609907), and I still think it's better to be explicit. Without explicit branch specification, vim-plug has no way to verify if the local clone is in valid state and I believe it's simply better to know in the first place that you're using a non-master branch considering that the author of the plugin can change the default branch at any time.

Most importantly, I've never had to use a plugin that does not use master branch and I don't want to complicate things (code-wise) for such exceptional cases. I'm going to close the issue as `wontfix`.

**Comment by rdnetto** [comment]
I'm aware that this issue has been closed now, but I thought I'd post anyway to explain why my plugin lacks a master branch. (I kinda wish you'd @mentioned me so I could have done so earlier.)

YCM-Generator originally had a master branch, and then later had a stable branch created. However, this resulted in many people cloning the master branch and either getting a bad impression of the project, or filing issues regarding it. (It's a development branch, it's going to be broken sometimes.) Consequently I renamed that branch to develop and made stable the default branch, to ensure that people either migrated to stable or made a conscious decision to use master. The naming of the branches was based on the [git flow](http://nvie.com/posts/a-successful-git-branching-model/) model, except that I did not name my production ready branch master since I thought that would cause confusion.

The reality is that the meaning and existence of the master branch varies from project to project, and relying purely on convention results in bad defaults, especially since `orig/HEAD` is already used to communicate the default branch to users.

At any rate, I just merged a PR to document this in YCM-Gen, so there's a workaround in place now (for my project anyway).

**Comment by starcraftman** [comment]
@rdnetto Hi. Well I think @junegunn made his opinion clear, so we aren't likely to revisit this.

I find your explanation a bit odd. It seems like it would have been a lot less effort/confusion if you had just stabilized master branch to be your production code, then made develop branch as your dev line. Just my opinion though.

**Comment by junegunn** [comment]
@rdnetto I see your point. But the (allegedly false) assumption makes the code of vim-plug simpler and easier to maintain. It works 99.9% of time, and it's not like we don't have a way around. Let's say that vim-plug requires you to be explicit about the branch to use and `Plug 'something'` is a shorthand notation of `Plug 'something', { 'branch': 'master' }`. Convention over configuration.

**Comment by rdnetto** [comment]
@starcraftman That's fair enough - I just wanted to explain the opposing viewpoint, especially since I think it's only a matter of time until this comes up again.
My justification at the time was that master was normally used as the development branch, and I didn't want to create further confusion. At any rate, changing it now would be disruptive to my users, so I'm stuck with it.

@junegunn I don't doubt it - I thought about how you'd go about implementing the correct behaviour and it is much more painful. It's not the choice I'd make myself, but then it's not my project either.

At any rate, YCM-Gen's README includes a note about the correct line for vim-plug, so it's a moot point now.
