### ISSUE TITLE
ANDing 'on': command with 'for': filetypes

### ISSUE THREAD

**Issue by indiofish** [junegunn/vim-plug#289]
Hi, I started using vim-plug instead of pathogen, and loving the 'snappy' startup it provides.

While toying with the lazyload options, I noticed that 
```vim
Plug 'foo/bar', {'on': 'command', 'for': 'c'}
```
would load bar for all C files, *or* on event mentioned, when what I wanted was loading bar on command, when editing C files.

Of course, I could just write
```vim
Plug 'foo/bar', {'on': []}
au sth *.c call plug#load('bar')
```
(I know that au events and 'on' commands are different, but just to illustrate it)
but I think it would be nice to keep loading conditions at the top, together, instead having to look into aus.

So I was wondering if you could provide something like
```vim
Plug 'foo/bar', {'for': 'c' & 'on': 'command'}
```
Of course, it's just a suggestion and hope I'm not wasting issues.

Thanks.

**Comment by junegunn** [comment]
I don't see the point.

> what I wanted was loading bar on command, when editing C files.

What is the expected result when you execute the command when editing non-C files? Do you want it to fail, because vim-plug should not load the plugin which implements the command as the condition is not met? Then why would you execute the command in the first place? Maybe you're misguided that you can specify any command on `on` option? e.g. non-user command, commands from other plugins. It would be much helpful if you give a real example.

Also, the options that follow the name of the plugin is just a vim dictionary, and the use of `&` is of course not a valid syntax.

**Comment by junegunn** [comment]
And you should ask yourself whether if you're over-optimizing stuff. On-demand loading of vim-plug does not always work and usually doesn't have any impact on the startup time if the plugin is carefully laid out to be "autoload"ed. See the output of `--startuptime` log before applying `on` or `for` option.

**Comment by indiofish** [comment]
Well I was going to load Syntastic on SyntasticCheck only for certain filetypes (some files tend to take some time during the checking, and this command is automatically run upon writing buffer) and was hoping that vim-plug would some how just ignore the command.
But I see your point on how SyntasticCheck should not be executed on the first place, so instead I specified filetypes in Syntastic options. (yes I guess I was a bit lazy... but was wondering if I could solve it with simple syntax of vim-plug without having to touch Syntastic.)
Thanks for the advice on startuptime, will look into that before finishing load settings.

Sorry for the inconvenience, will close this issue... and thanks for your support & writing such a great plugin manager :).

**Comment by junegunn** [comment]
Thanks for the explanation. Yeah it's beyond the scope of vim-plug.
