### ISSUE TITLE
Plugin Collection via vim-plug?

### ISSUE THREAD

**Issue by hyiltiz** [junegunn/vim-plug#296]
I am wondering if Plug can install and generate help for a plugin which contains somewhat separate plugins like this one: https://github.com/WolfgangMehner/vim-plugins.

Or should we use a self-made hook to split the files after installing?

**Comment by starcraftman** [comment]
Hello @hyiltiz  Dealing with your questions in order.

vim-plug will run helptags only inside a plugins `doc` dir, so assuming that is all the docs you want to make available that will be fine.

Other than that, vim-plug just makes the plugin available on the rtp and assumes it runs as is. If you need post install steps, you will have to prompt users on startup to do so manually or write some post install script they can invoke in bash or python. Regarding the latter, please see [update hooks](https://github.com/junegunn/vim-plug#post-update-hooks).

It seems to me those plugins should be in separate git repos if you really want people to use it with vim-plug or such managers. Shipping them all together forces people to download all that stuff even if say they only want bash support. Also, the tags file is rather large at 116k, since all the docs are together.
