### ISSUE TITLE
Suggestion: Highlight modified repositories during PlugUpdate

### ISSUE THREAD

**Issue by expipiplus1** [junegunn/vim-plug#297]
When PlugUpdate opens a very narrow split it can be hard to determine which repositories have changed. It would be helpful to perhaps replace the `-` character at the beginning of the line with a `^` or `+` for the repositories which have a new revision.

**Comment by junegunn** [comment]
Thanks for the suggestion. Maybe this is a matter of personal preference, but I don't think it's really needed. And I try not to change the installer unless necessary since it's a bit painful to update 3 different versions of installer (ruby, python, and vim/neovim) in a consistent manner. (Instead of changing those installers we can update the bullets at once after the parallel installation is finished, but then it won't look as slick as I'd like it to be.)

A couple points to note:
1. vim-plug will open its window in a new tab (fullscreen) instead of in a vertical window if you set `let g:plug_window = 'tabnew'`.
2. If I want to see the changes after `PlugUpdate`, I can simply press `D` to start `:PlugDiff` command which provides detailed information about the changes.

**Comment by expipiplus1** [comment]
Cool stuff, those alternatives sound ideal.
Thanks
