### ISSUE TITLE
Error after update/install

### ISSUE THREAD

**Issue by khalidchawtany** [junegunn/vim-plug#314]
Each time I run any of ```PlugUpdate / PlugInstall``` command, I get the error below. After the error message by a second, it disappears, as if **<CR>** is feed to it, to simulate press Enter prompt.
```
Error detected while processing function <SNR>2_job_handler..<SNR>2_tick..<SNR>2_upd
ate_finish..<SNR>2_finish..plug#end:
line   50:
E183: User defined commands must start with an uppercase letter
```

**Comment by junegunn** [comment]
Looks like you have invalid config in your vimrc, i.e. lowercase command in `on` option. Please post your vimrc.

**Comment by khalidchawtany** [comment]
Awch :(
You were right, I had ```'on': ['obsess']``` instead of ```'on': ['Obsess']```

Sorry for the noise, and many thanks for your great plugins ;)

**Comment by junegunn** [comment]
Well, I think the message is pretty straightforward, but I realized that there's more fundamental problems.

1. You don't see the error message upfront when you start vim.
1. The current code was written to [check](https://github.com/junegunn/vim-plug/blob/8292b3f31a9cf77cf6278758db560eeb37fbec10/plug.vim#L178) if an arguments to `on` option starts with an uppercase letter and ignore it otherwise. However, `cmd =~ '^[A-Z]'` can return true even if cmd starts with a lowercase letter when `&ignorecase` is set, which is what you just experienced.

Both problems are trivial to fix. I'll fix them.

**Comment by khalidchawtany** [comment]
Lovely :+1:
