### ISSUE TITLE
Supporting a 'commit' option to specify a SHA

### ISSUE THREAD

**Issue by jfelchner** [junegunn/vim-plug#315]
I just read through #181 and looked at the FAQ, but I want to bring up what I think is an important point.

Yes, it would be great to be able to use a branch.  Yes, it would be great to be able to use a version tag, but a lot of plugin authors don't tag their releases.  A lot of plugin authors just commit to `master`.

Sometimes there's a bug in a plugin and the _only_ option is to lock the plugin to a specific SHA until it's fixed.

I'm loving `vim-plug` on Neovim so far :heart:, but broken plugins happen _all the time_ and if this project is going to be a plugin _manager,_ I think this is a must-have feature.

Thanks! :grinning:

**Comment by jfelchner** [comment]
Also, for the record, this happened to me on the first install of a plugin and therefore `frozen` doesn't help.

**Comment by junegunn** [comment]
> Also, for the record, this happened to me on the first install of a plugin and therefore frozen doesn't help.

Yeah, in that case, you'll have to "unshallow" the repo (`git fetch --unshallow`) and check out the commit you want, I can see that can be a little cumbersome, but it's at least not impossible. And we can write an external helper script, function, or command that makes the process easier.

```vim
function! s:plug_reset(name, sha) abort
  let chdir  = 'cd '.fnamemodify(g:plugs[a:name].dir, ':S')
  let cursha = systemlist(chdir.'&& git rev-parse HEAD')[0]
  if v:shell_error
    echoerr cursha
  endif
  if stridx(cursha, a:sha) == 0 || stridx(a:sha, cursha) == 0
    echom printf('%s is already on %s', a:name, cursha)
  else
    let log = system(chdir.'&& git fetch --depth 999999 && git reset --hard '.a:sha)
    if v:shell_error
      echoerr log
    endif
    echom printf('Resetted %s to %s', a:name, a:sha)
  endif
endfunction
```

(Note that I didn't bother to make this implementation compatible with `PlugDiff` which relies on git reflogs, but it doesn't make sense in these kind of situations plugins anyway.)

Another obvious workaround is to fork the repo and use it until the bug is fixed.

> but broken plugins happen all the time

We've discussed about the feature a few times in the past, but I was always not convinced that it's worth it, because

1. I personally think it's fundamentally wrong to use commit hashes from user's side.
2. It complicates the implementation significantly especially considering that we have three different versions of installers. Also note that we try to make vim-plug work even on very old versions of git, and the task of making a seemingly trivial feature work consistently across different versions usually turns out to be surprisingly painful and tedious. I could be wrong though.
3. I never really needed it that much often. There are always alternative Vim plugins so I simply ditch plugins that are not reliable.
4. We can always tell the users to use neobundle instead :)

@starcraftman How do you feel about this? I think I made myself clear that I'm not really into it, but I may change my mind, who knows.

**Comment by starcraftman** [comment]
@junegunn Personally, I've rarely had a major plugin I use break, if it did I'd just manually step it back a few commits as you suggested.

My only concern is that adding such support will only further complicate plug.vim for little real benefit. It is a corner case that most users probably won't make use of.

Supporting it via the python installer shouldn't be difficult. Long as you are certain it is what you want to do.

@jfelchner Can you give me some examples of plugins you use that break often? I may be able to recommend others.

**Comment by jfelchner** [comment]
@starcraftman ctrlp just broke on me.

The thing that I'm confused about (and I don't know VimScript so please forgive me) is that in git, branches, tags, and commits all get checked out the same way so why isn't there just a `ref` option? Let the ref take any valid git ref and be done with it. Why does vim-plug even care about the ref type?

**Comment by starcraftman** [comment]
@jfelchner Are you using [kien's](https://github.com/kien/ctrlp.vim) or the new active [fork](https://github.com/ctrlpvim/ctrlp.vim)? I'd recommend latter. I just checked and the fork works for me. Have you tried disabling ctrlp plugins/other parts of vimrc?

As to second question, a previous user requested we substantially cut down on bandwidth so when available (i.e. git new enough) we do light checkouts with `--depth 1`. These kinds of checkouts don't support normal checkouts until you `--unshallow` them. Were it not for this patch, you would otherwise be correct.

**Comment by junegunn** [comment]
@jfelchner 

> Why does vim-plug even care about the ref type?

That's what I initially had in mind, but we ended up realizing that we can't reliably use the same set of commands for tags and branches. See #174 for the details.

@starcraftman I would rather not put more logic to the installers. Instead, post-processing it as in https://github.com/junegunn/vim-plug/commit/2fc7a7f730ee0abfbee6d4d52d35fa394d845204. Not sure if we're really going to do this though, need more careful consideration.

**Comment by starcraftman** [comment]
@junegunn A reasonable approach. Up to you then.

**Comment by jfelchner** [comment]
Yeah up to you guys. It seems like part of the issue is the desire to be compatible with extremely old versions of git, which I think (personally) just gives you diminishing returns every additional day. 1.7 is literally so old that the git repo doesn't even have a version tag for it. 😳

**Comment by junegunn** [comment]
> the desire to be compatible with extremely old versions of git

Yeah, sadly I have to deal with a bunch of archaic RHEL5 servers with git 1.7 or 1.8 at work  :) 
Extreme backward compatibility is something I do need at the moment, so it won't go away in a near future.

**Comment by jfelchner** [comment]
@junegunn amazing!  Thank you so much!!! :grinning:
