### ISSUE TITLE
Not an editor command: plug#begin('~/.vim/plugged')

### ISSUE THREAD

**Issue by turnabout** [junegunn/vim-plug#325]
I'm trying to install vim-plug. I've copied plug.vim in the ~/.vim/autoload directory.

This is my .vimrc content right now:

```
" Vim plug
plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf'
plug#end()
```

When I start vim, I get these error messages printed to the terminal:

```
Error detected while processing /home/kevin/.vimrc:
line    2:
E492: Not an editor command: plug#begin('~/.vim/plugged')
line    4:
E492: Not an editor command: Plug 'junegunn/fzf'
line    6:
E492: Not an editor command: plug#end()
```

And any plugin fails to load, of course.

I'm using Ubuntu 15.05.

**Comment by starcraftman** [comment]
@turnabout Hello. Please see the [example vimrc](https://github.com/junegunn/vim-plug#example). The problem is you forgot the keyword `call`. plug#begin is an autoload function not an editor command. Once the script is sourced, Plug & the associated commands are available.

You may wish to read a more complete explanation at [Learn Vimscript The Hard Way](http://learnvimscriptthehardway.stevelosh.com/chapters/53.html)

**Comment by turnabout** [comment]
Ah, that was silly of me. Thank you.

**Comment by starcraftman** [comment]
@turnabout No problem, have fun with vim. :)
