### ISSUE TITLE
Error when running any vim-plug command

### ISSUE THREAD

**Issue by kishikaisei** [junegunn/vim-plug#326]
When I ran any vim-plug command (PlugInstall, PlugClean...) I get the following error:

![azhrv](https://cloud.githubusercontent.com/assets/1894123/11391820/afeae67c-9355-11e5-80f3-ee38fce646ca.png)

Vim plug worked fine for a while, but I am unsure what happened so it broke. I tried redownloading vim-plug and replacing it but to no avail.

I am running windows 10, vim 7.4, and cmder.

**Comment by starcraftman** [comment]
@kishikaisei Hi. Warning off the bat, the dreaded E484 is a catchall error that can have several causes so diagnosing may require a bit of patience. One cause is bad shell escaping, but I believe we dealt with all that some months ago and it hasn't changed since. For now we'll focus on the other causes.

1. Just so we know what shell is taking the commands, paste the output of `echo &shell`.
1. Please [read](https://github.com/junegunn/vim-plug/wiki/faq#windows-system-error-e484) and try the reg queries to check for scripts interfering with the shell.
1. Check that you have write permission at the temp directory. The temp directory is set in either $TMP or $TEMP. Do `echo $TMP $TEMP` to see their values. Then, go to the folder and see if you can make a folder. See [Generic Causes](http://vim.wikia.com/wiki/Fix_errors_that_relate_to_reading_or_creating_files_in_the_temp_or_tmp_environment_on_an_MS_Windows_PC) for information.

Hopefully it gets fixed after those steps.

**Comment by kishikaisei** [comment]
Thank you for your help;
I tried your steps;
1. the result for `echo &shell` is `cmd`.
2. I tried both commands, both returned: `ERROR: The system was unable to find the specified registry key or value`
3. the result for both was: TMP and TEMP `C:\Users\KISHIK~1\AppData\Local\Temp` to wich I have RW access. I changed the Temp to `C:\TMP` the result is the same.

**Comment by starcraftman** [comment]
@kishikaisei Interesting. The curious thing here is you say it worked before then stopped. Can you try executing a system command for git to see if executing normal commands works. Like following: `echo system('git --help')`. If that doesn't work, maybe it is an escaping of a particular plugin.

If above fails, please provide me your vimrc that you use on Windows. I'll try it. I just tested mine on Windows 7 and it works.

**Comment by kishikaisei** [comment]
Running `echo system('git --help')` returns the help for git, as expected. :)
[Here is my _vimrc]
(https://gist.github.com/kishikaisei/ebe372677bcfb90d8cba)
I used vim-plug to install all my plugins, so at some point it worked well, but now I can't PlugClean the unused plugins, or anything else really...

**Comment by starcraftman** [comment]
@kishikaisei Hi again. Sorry for the late reply, this might be a bit lengthy but please read, I do know your problem. I believe it is a config issue, I should have asked for the vimrc earlier. The part that is breaking your config is below. At least it broke my vim.

```viml
    set shell=cmd
```
Firstly, in my experience you should not set either `shell` or `shellcmdflag` manually without a good reason, on Windows the default will almost always be your batch cmd.exe prompt (a full path, so it need not be on $PATH). Most importantly, even if it was on your path it should be cmd.exe on Windows. If you remove/comment lines 19-26 vim-plug should work again.

Overall, try and be a bit careful with what you put into your vimrc. The wrong setting can break vim. Also, don't be shy about seeing the helpdocs (i.e. `:h shell` or `:h term`).

A few additional notes:
```viml
 set shellcmdflag=/c
```
This should be your default, unless you choose a shell that isn't cmd.exe. You can see your default with `set shellcmdflag?`. You can safely remove this line.

```viml
" Enable filetype plugins
filetype plugin on
filetype indent on
```
These lines aren't needed, vim-plug handles this for you.

```viml
    set term=xterm
    set t_Co=256
    let &t_AB="\e[48;5;%dm"
    let &t_AF="\e[38;5;%dm"
```
These are settings for a posix shell, ansi codes don't work on the cmd prompt on Windows. You should see `:h term` for more info on that setting. I think you put them in the wrong section.

```viml
    let $TMP="c:/TMP"
```
You won't need this anymore.

I hope all works now, close if yes.

**Comment by kishikaisei** [comment]
Thank you for your help, but, when removing the lines specified, it quite breaks vim:
![cmder](https://cloud.githubusercontent.com/assets/1894123/11544274/511eb618-9941-11e5-84b4-40b902a0bc8d.png)
And even when running  `:PlugClean` not only it "detects" all my plugins as "unused"
, but when asked if I want to proceed anyway, this error is thrown:
![error](https://cloud.githubusercontent.com/assets/1894123/11545575/42c1978c-9948-11e5-9dba-be2b804fe718.png)
So yeah, removing the lines from vimrc didn't help much... :/

**Comment by starcraftman** [comment]
@kishikaisei Ah. I'm sorry, your using cmder. I totally forgot when trying your vimrc, hence my confusion. Ignore most of the comments, though the one regarding filetype plugin on should remain valid.

I don't really know anything about cmder to be honest. I'll try it if I get a chance. I assume since you are setting /c flag that it is a Windows based shell with improvements, something we do escaping commands must not agree with it.

**Comment by kishikaisei** [comment]
Hi @starcraftman even after deleting those lines, and running PlugClean in GVim or CMD, the same error is shown, so I don't think it's because of cmder? It is quite confusing :/

**Comment by kishikaisei** [comment]
Using my original .vimrc, I found out that if I remove the folder "bundle" vim-plug behaves just fine... But once I have launched the "PlugInstall" command and let it finish, any vim-plug command will throw the error I mentioned, so, is it possible that there is some compatibility issues? I will try to install plugins one by one and keep you updated :)

**Comment by kishikaisei** [comment]
Well the error is shown after that I install any plugin at all...
I am out of ideas...

**Comment by kishikaisei** [comment]
Hi, after a clean installation of windows, it worked fine, so I guess this can be set as resolved, since I can't, for now, reproduce the issue.
Sorry and thank you for your help.
Keep up the good stuff :)

**Comment by starcraftman** [comment]
@kishikaisei Well that's good to hear. Sorry it took a Windows reinstall to resolve, that can be a terrible nuisance. I'll close this for now.
