### ISSUE TITLE
Plug only adds one of my unmanaged plugins to the runtime path

### ISSUE THREAD

**Issue by hugomg** [junegunn/vim-plug#335]
Using the following .vimrc, only the "ocp-indent/vim" directory ends up being added to the runtime path (as tested via `echo &rtp`). The "merlin/vim" directory is NOT added to the runtime path as I would expect.

    set nocompatible
    set shell=/bin/sh  " vim does not like that I use fish

    call plug#begin('~/.vim/plugins')
      Plug '~/.opam/4.02.3/share/merlin/vim'
      Plug '~/.opam/4.02.3/share/ocp-indent/vim'
    call plug#end()

According to my tests, the last "Plug" command is the only one that matters when it comes to unmanaged plugins. If I swap the order in my example then merlin gets added to the rtp instead of ocp-indent and if I add a third plugin the last one in the list is still the only one that appears in the runtime path.

**Comment by junegunn** [comment]
vim-plug infers the name of the plugin from the given path. Both paths you use end with `/vim` and vim-plug sees both

**Comment by junegunn** [comment]
Oops. Pressed the wrong button while typing.

vim-plug infers the name of the plugin from the given path. The both paths you use here end with `/vim` and vim-plug thinks they are both plugins named `vim`, and since it does not allow plugins with the same name, only the last one survives.

There are two ways to fix it

1. Assign different names to the paths
2. They don't seem like conventional plugins. If they are just some custom vimscripts and you're simply interested in having them on `&rtp`, `set rtp+=~/.opam/4.02.3/share/merlin/vim` should suffice.

**Comment by junegunn** [comment]
IF they are actual plugins, `Plug '~/.opam/4.02.3/share/ocp-indent', { 'rtp': 'vim' }` might be what you're looking for.

**Comment by hugomg** [comment]
Thanks, using the `{'rtp' : 'vim'}` option fixed things!
