### ISSUE TITLE
Managing my own plugins

### ISSUE THREAD

**Issue by vito-c** [junegunn/vim-plug#338]
What's the best way to have vim-plug manage my own plugin that I'm writing? I changed the config but vim-plug got all angry at me.
````
x jq.vim:
    Invalid URI: git@github.com:vito-c/jq.vim.git
    Expected:    https://git::@github.com/vito-c/jq.vim.git
    PlugClean required.
````

**Comment by junegunn** [comment]
1. Using full URL
```vim
Plug 'git@github.com:vito-c/jq.vim.git'
```

2. Using `g:plug_url_format`; see what I'm doing [here](https://github.com/junegunn/dotfiles/blob/master/vimrc#L15-L44)

**Comment by vito-c** [comment]
thank you!

**Comment by xarthurx** [comment]
@junegunn 
This need to upload my own under-dev plugin to git for every new changes.
While during developing, this will not help in a fast test-out way where I change some code and test.

Is there a better way to do it? say some flag so that vim-plug will not trace the git location for a local git repo?
