### ISSUE TITLE
Not Working on Windows

### ISSUE THREAD

**Issue by siqi-liu** [junegunn/vim-plug#353]
It used to work well, but after the recent update, now whenever I call `PlugUpdate/PlugInstall`, I get errors like:

`fatal: could not create work tree dir 'D:\vimfiles\plugged\nerdtree" '.: Invalid argument`

**Comment by starcraftman** [comment]
@siqi-liu Hello. How exactly are you using vim-plug on Windows? GVim vs terminal vim? Msys2 or msysgit?

Also, if you do `PlugInstall 1` does it still give errors?

**Comment by siqi-liu** [comment]
Thanks for the quick response. Running `PlugInstall 1` does not give errors. I'm using GVim. I'm only using msysgit. Pretty old version though (Git-1.9.5-preview20150319).

**Comment by starcraftman** [comment]
@siqi-liu Interesting, probably a problem with python installer then, since 1 worked. Appears to be a path/escaping problem. I assume you have python installed and that `D:\vimfiles` actually exists.. What's the output of the following commands:

- `:echo &shell`'
- `:python import sys; print sys.version_info[0:3]`
- `:python3 import sys; print(sys.version_info[0:3])`
- `:!ls D:\vimfiles\plugged` (If that fails, `:!dir D:\vimfiles\plugged`)

The git version shouldn't be a problem, we work on older.

**Comment by siqi-liu** [comment]
- `C:\WINDOWS\system32\cmd.exe`
- `(2, 7, 10)`
- This one gives an error since I do not have python3 here.
- This one lists the folders of plugins I installed. Since I just successfully ran `PlugInstall 1`, it looks fine.

**Comment by starcraftman** [comment]
@siqi-liu Alright, I've identified the problem I believe. Just to confirm can you do the following small edit to your plug.vim.

Line 277 should read  `return s:path(a:path) . '\'`, change it to  `return s:path(a:path)`. Please try again PlugInstall, it should work.

**Comment by siqi-liu** [comment]
@starcraftman After the change, if I remove all the plugins and freshly run `PluginInstall`, it works. However, after that, if I run `PlugInstall` or `PlugUpdate`, it shows errors:
`fatal: Not a git repository (or any of the parent directories): .git`
But `PlugUpdate 1` works.

**Comment by starcraftman** [comment]
@siqi-liu Ok, confirms what I thought. Appears the problem was trailing slash on the directory given to the clone command. I'll do a bit more testing on my VM, patch should be available soon. Until then, you should continue using `PlugInstall/Update 1`. Alternatively you can set `let g:plug_threads = 1` in your vimrc to save yourself typing 1 all the time.

Also, just to be clear, when threads are 1, the plain VimL installer is running. Hence why no error.

**Comment by starcraftman** [comment]
@siqi-liu Do a `PlugUpgrade`, should work now. I confirmed on my local VM this fix.

**Comment by siqi-liu** [comment]
@starcraftman Thanks for the patch. It works for `PlugInstall`, but `PlugUpdate` gives the error I mentioned previously:
`fatal: Not a git repository (or any of the parent directories): .git`
Did I miss something?

**Comment by starcraftman** [comment]
@siqi-liu Oh now I feel stupid, it was that dastardly batch cd gotcha. Forgot to put /d to ensure the cd commands to other drives work. Didn't com up in testing because I always use same drive letter.

Just to confirm, can you make the following small change to line 1174 and confirm you work:
```viml
 self.cmd = 'cd {0} && {1}'.format(cmd_dir, self.cmd)
```
```viml
 self.cmd = 'cd /d {0} && {1}'.format(cmd_dir, self.cmd)
```

Sorry for the inconvenience :/.

**Comment by siqi-liu** [comment]
@starcraftman No problem. I confirm, with that change, `PlugUpdate` works now.

**Comment by starcraftman** [comment]
@siqi-liu Thanks for reporting and patience. Should be all sorted now. Happy vimming :).
