### ISSUE TITLE
PlugSnapshot and shallow clones

### ISSUE THREAD

**Issue by junegunn** [junegunn/vim-plug#355]
A script created by `PlugSnapshot` will not work nicely with shallow clones. Apparently I should have addressed the problem when I added shallow clone support.

```
vim +PlugUpdate +qa

PLUG_HOME=~/.vim/plugged

cd $PLUG_HOME/goyo.vim/ && git reset --hard 630f5d8
```

`PlugUpdate` will create a shallow clone, and `git reset` will fail to find the commit locally.

I can think of two ways to fix this:
- Add `git fetch --unshallow` to each line
    - Guaranteed to work
    - Unshallowing one-by-one, slow
- `vim +'let g:plug_shallow = 0' +PlugUpdate +qa`
    - Smaller script. Faster execution.
    - May not work with plugins that are already installed

I prefer the latter for now.

---

It has been broken for ages, and no one noticed the problem. This is to me another evidence that very few actually care about these "advanced" features and we should not be adding random stuff people ask for. Even they won't use it in the end.

**Comment by vyp** [comment]
Actually I was thinking about this quite some time ago, when I used to use `:PlugSnapshot`. But instead of asking about it, I just switched to using submodules to manage vim plugins (with vim-plug), which isn't really a solution of course. (It's because I figured that `:PlugSnapshot` might be broken/unreliable so I decided the easier/lazier option was to use submodules.) I probably should have reported here, sorry. Although with saying this, now that I use submodules, I don't mind if you remove `:PlugSnapshot`.
