### ISSUE TITLE
YCM Lazy Load Improperly Cleaned On Exit

### ISSUE THREAD

**Issue by agauniyal** [junegunn/vim-plug#372]
https://github.com/Valloric/YouCompleteMe/issues/1874

**Comment by starcraftman** [comment]
@agauniyal I did some quick tests, can confirm there is a bug. It appears that when lazy loading two ycmd servers are being started and only one is correctly being closed on vim's exit. Can be confirmed by doing (with vimrc set to lazy load):

```sh
killall python2
pgrep python2
vim ./file.cpp (then quit)
pgrep python2
```

Will look into it further in a bit. Also, I'm editing your title. It is fairly inaccurate.

**Comment by junegunn** [comment]
@starcraftman I was also testing it and it's not a bug of vim-plug. The problem is YCM starts ycmd daemon process whenever `youcompleteme#Enable()` is called even if one is already running. The reason we guide the users set up `User` autocmd is YCM initializes on `VimEnter` event, but if a user starts vim with a file argument e.g. `vim foo.cpp`, both `VimEnter` and `User` event are triggered leaving two daemon processes hanging. Considering that they are probably not going to prevent this duplicate daemon problem, we should update the example as follows:

```vim
autocmd! User YouCompleteMe if !has('vim_starting') | call youcompleteme#Enable() | endif
```

**Comment by starcraftman** [comment]
@junegunn Ah I see, makes sense. Thanks for the explanation.

**Comment by junegunn** [comment]
Updated the doc. Let me know if you see any problem. It's a bit sad to lose the conciseness of the example.
