### ISSUE TITLE
Please document basic commands in vim help file.

### ISSUE THREAD

**Issue by chrisbra** [junegunn/vim-plug#388]
As per the title. Thanks.

**Comment by junegunn** [comment]
This was discussed before in #234, but we were unable to reach a satisfactory conclusion as `plug.vim` was designed to be distributed as a standalone vim script file. As noted in the issue, I can easily make a help file, but we'll have to decide where to put it.

**Comment by chrisbra** [comment]
Hm, I don't follow what would be so terrible bad about putting the documention below `~/.vim/doc` After all, that's what the directory is for. But perhaps you want to distribute the plugin additionally as vimball for those who want documentation. I would then just download the .vba file and be done with it.

**Comment by junegunn** [comment]
What I meant by "where to put it" in the above comment was about the position of the file in this git repo. I was worried about this repo having `doc` directory as it can give the wrong impression that it is "pathogen-compatible". Anyway, I have no objection on the use of `~/.vim/doc`. I was just saying in the previous discussion that vim-plug should not "automagically" put things into the directory without the user's consent.

**Comment by chrisbra** [comment]
okay, I understand. Therefore I made it self-extractable #390

**Comment by starcraftman** [comment]
Uh, this again. I dunno, in #234 I argued for it, I've since changed my mind. I don't see much point for the fuss we will need (like stuffing the doc into plug.vim as you did and then extracting).

Let me ask you @chrisbra , what questions exactly would you have done `:h vim-plug` for? Apart from the information needed to do initial startup/conversion to vim-plug I find vim-plug to be very intuitively named with regards to commands/options. I'd argue since most people will stumble upon vim-plug via their browser (i.e. r/vim, github, so on) they will read the README while converting. I suspect only a handful of less used options/flags would ever be consulted.

As to location, I git manage my vim folder (as quite a few do) and would not like it in `~/.vim/doc`. Would require me ignoring another folder. More importantly, vim-plug has permission to write to the path passed to `plug#begin()`, it shouldn't write elsewhere.

**Comment by chrisbra** [comment]
@starcraftman 
1) I wanted find out, what arguments are allowed for the various `:Plug` commands. #389 
2) Supposedly, there are people, who don't have internet all the time available. And I don't like having to find the README.md file manually and reading it. That is much more trouble than saying `:h plugin.txt`
3) I don't understand. ~/.vim/doc is exactly for that kind of thing. plug.vim resides in ~/.vim/autoload so the documentation should be in ~/.vim/doc
4) I don't understand the argument about vim-plug having no permission to write elsewhere. I don't believe this.

**Comment by starcraftman** [comment]
@chrisbra 
1) Fair enough.
2) Without internet you can't do much with vim-plug since clones are depth 1. I agree `:h vim-plug` is quicker than Googling vim-plug, though not by much considering my browser is always open.
3) In my opinion, because vim-plug doesn't follow the standard plugin spec, this connection doesn't follow. Even if it did, I don't think everyone will agree with it given past expectations.
4) Well I do. I don't like clutter I didn't ask for/won't use, especially in a folder I manage.

Let us say we don't do help doc generation automatically as junegunn stated in his last response. Then it follows that a user would have to do some action "X" to generate them. How does said user find out about "X"? Goes to README? Brings us back to step 1. 

Don't take this personally, I'm always critical of things. I had more thoughts but decided against enumerating a larger list. Not my call anyway, I think my position is clear though.

**Comment by chrisbra** [comment]
Apparently, there is no interest in such a solution. Closing

**Comment by junegunn** [comment]
vim-plug has always been a single vimscript file, and adding/maintaining another file gives us headaches.

We have pretty [nice comment section](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1-L43) at the top of the script that can be accessed offline. Maybe we could extend the section a bit to cover the list of the commands and possibly provide an extra command (`:PlugHelp`?)` that simply "echo"es the section.

**Comment by chrisbra** [comment]
i think that is more effort and additionally, echoing won't help. By the time you type something, you possibly don't see the output not anymore. Plus you can't copy/paste. So no, I don't think that echoing is the solution. Updating the comment section should be enough for the moment.

**Comment by brcolow** [comment]
https://github.com/google/vimdoc might be worth checking out for this case.

**Comment by mgedmin** [comment]
I was about to file this issue, but then did a search and found it was already filed.  I love everything about vim-plug, except its lack of native vim `:help`.  The things I usually want to look up are the keybindings in the :PlugUpdate window, but a list of :Plug commands and their allowed options would also be nice to have.

`:PlugUpgrade` already writes directly into `~/.vim/autoload`, so I don't think anyone would be mad if it also wrote into `~/.vim/doc`.

**Comment by junegunn** [comment]
```vim
command! PlugHelp tabedit https://raw.githubusercontent.com/junegunn/vim-plug/master/README.md
```

**Comment by chrisbra** [comment]
that is barely an alternative.
