### ISSUE TITLE
clarify in docs that GitHub is the default plugin source

### ISSUE THREAD

**Issue by wolftune** [junegunn/vim-plug#397]
There seems to be nothing in the docs clarifying that some plugin syntax 'blah/someplug' is GitHub. There shouldn't be any assumption that everything lives on GitHub, even though in practice that's the case today.

I'd like to see it stated explicitly that GitHub is the default for that syntax and also see examples of alternate syntax for other plugin source repositories.

**Comment by junegunn** [comment]
> I'd like to see it stated explicitly that GitHub is the default for that syntax and also see examples of alternate syntax for other plugin source repositories.

I think it's already given in [the examples section](https://github.com/junegunn/vim-plug#example):

```vim
" Using git URL
Plug 'https://github.com/junegunn/vim-github-dashboard.git'
```

Any valid git URL is allowed, even ones like `file:///....`.

How vim-plug interprets `USER/REPO` argument *by default* can be configured by setting `g:plug_url_format` as described in https://github.com/junegunn/vim-plug#global-options. So one might argue that the default source resolution is at least indirectly stated in the document but I agree that it can be not so obvious to the users who are not familiar with Vundle tradition. vim-plug was initially written as an alternative to Vundle and inherited its behavior. Vundle was immensely popular among vim users at the time, so I thought it should be obvious to most users.

I'm open to any suggestions to the README page as long as it doesn't make it too verbose.

**Comment by pickfire** [comment]
@junegunn I didn't notice that `file:///...` is also allowed, nice one, I hope that it is documentated.

**Comment by wolftune** [comment]
> >    I'd like to see it stated explicitly that GitHub is the default for that syntax and also see examples of alternate syntax for other plugin source repositories.

> I think it's already given in the examples section:

The sentence you're quoting there has two parts. Yes, the example shows one alternate syntax, but it *also* points to github, so there's no indication that anything other than github can be used.

But the real point is, most syntax is just 'blah/something', and nowhere in the docs does it state explicitly that this assumes GitHub. It should say something like "this syntax goes to GitHub. For sources outside GitHub use…"

Right now, this is all not very clear.

**Comment by junegunn** [comment]
> so there's no indication that anything other than github can be used.

The comment for the line says it's "Using git URL". A "git URL" is universal and of course not limited to GitHub. There's no reason to think that way unless the user has no prior experience with git. But, we can consider changing the example to non-github URL. Like, ... hmm it's kind of funny that it's hard for me to think of a relevant, popular plugin that is not hosted on GH.

```vim
" Using shorthand notation; by default points to github.com
" Make sure you use single quotes
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/vim-easy-align'

" Using git URL (TODO: any good example?)
Plug 'https://bitbucket.com/foo/bar.git'
```

Is it clearer?

> Does it support the wider range of syntax options

Can you elaborate? I'm not familiar with those. FYI, If you can't find a feature that is in Vundle but not in vim-plug, that is probably because we decided that it is not necessary.

**Comment by wolftune** [comment]
yes, the "by default points to github.com" is better. I think I would make it:

`Shorthand notation points to github.com by default` (without the "using" word)

For other options, here's what Vundle has:

```
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
Plugin 'user/L9', {'name': 'newL9'}
```

I do notice that command-t is now on GitHub and so are the vim-scripts. I think just a dummy example makes sense like:

```
any git repo can be used in the form of:
Plug 'https://example.com/foo/bar.git'
```

I don't know if vim-plug supports the other functionality there that Vundle has or not, but if it *does* support it, some documentation up front makes sense.

**Comment by junegunn** [comment]
> Plugin 'L9'

This is equivalent to `Plugin 'vim-scripts/L9'`, which is actually supported by vim-plug, but we decided to deprecate it, so it's intentionally undocumented.

`git://git.wincent.com/command-t.git`, `file:///home/gmarik/path/to/plugin` are all proper git URLs. So to me it feels like stating the obvious repeatedly. I'm obsessed with keeping the doc short and concise, so please bear with me.

The supported options are listed in https://github.com/junegunn/vim-plug#plug-options. Also, more examples in https://github.com/junegunn/vim-plug#plug-options and https://github.com/junegunn/vim-plug#post-update-hooks.

**Comment by wolftune** [comment]
Thanks, I like short and concise :)

In the plug-options part, please say "Branch/tag/commit of the GitHub repository to use" as that will make everything really clear. I don't find it obvious that everything is on GitHub. Certainly there may be a future when more things are on GitLab or elsewhere, and there are people who dislike GitHub's centralized proprietary ecosystem…

My opinion is *not* to add all the long junk from Vundle. I like vim-plug's concision.

I just want GitHub stated explicitly and using a non-github git url will also just make the situation more obvious without adding any extra length to the docs. If you like the wincent example, that's fine with me.

**Comment by starcraftman** [comment]
Regarding this:

> " Using shorthand notation; by default points to github.com
" Make sure you use single quotes
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/vim-easy-align'

I might suggest instead something crystal clear like the following. One plugin is enough.

```viml
" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'
```

>" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
Plugin 'user/L9', {'name': 'newL9'}

This is all supported with some caveats:
- As @junegunn said we don't publicize, the vim-scripts depends on vundle's scraper and we don't control how often it runs or if it is even correct (there have been bugs like repo collisions). Also, they were always on github.
- Regarding `file://` this is more a feature of git protocol rather than Vundle or vim-plug. Moreover, I think most people would be happier with the '~/path/to/plugin` (which is documented). The former makes a clone only of commited work, the latter simply puts the path on RTP allowing you to instantly see uncommitted work.
- Note 'name' is 'as' for vim-plug.

You suggested:

> any git repo can be used in the form of:
Plug 'https://example.com/foo/bar.git'

We could use this instead of:

>" Using git URL
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

I suggest comment be changed to:

```viml
> any valid git URI is allowed
Plug 'https://example.com/foo/bar.git'

**Comment by junegunn** [comment]
@wolftune 
> In the plug-options part, please say "Branch/tag/commit of the GitHub repository to use" as that will make everything really clear.

Uh, no. Branch, tag, and commit are not limited to GitHub. I'm not sure how you get the idea that they only apply to git repositories hosted on GitHub. `Plug 'https://example.com/foo/bar.git', {'tag': '1.0'}` is a perfectly valid specification. (And those who don't like GitHub default can even change it with `g:plug_url_format`.)

@starcraftman I agree with your suggestions. By the way, URI or URL? They are simply interchangeable in git context? Git documentation seems to use URL; https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository#Cloning-an-Existing-Repository

**Comment by wolftune** [comment]
Thanks for the clarification. I think I've made the concern about clarity re: GitHub and I trust your judgment to address the issue concisely. Cheers.

**Comment by starcraftman** [comment]
@junegunn Good point, I guess we should stick to what git uses. So 'URL' with caps.
