### ISSUE TITLE
update feature

### ISSUE THREAD

**Issue by coachshea** [junegunn/vim-plug#406]
I know it's been discussed several times as to the possibility of vim-plug updating itself and I understand, and agree with, the reasons why it doesn't, but I was wondering if you thought it was worth considering a feature in which, during an update, a simple check to see if a new version was available was performed and, if so, a message was echoed (i.e. 'Vim-Plug upgrade available').

**Comment by junegunn** [comment]
vim-plug is pretty stable and if it works in your env, I think there's little reason to upgrade it. But if you still want to make sure that you're using the latest revision, why don't you just run `PlugUpgrade` after `PlugUpdate`? You can consider using a helper command like follows:

```vim
command! PU PlugUpdate | PlugUpgrade
```

**Comment by starcraftman** [comment]
@coachshea Alternatively, you could use a command to do this, like `vim +PlugUpdate +PlugUpgrade +qa`. This can be put as an alias in your shell init or in a shell script. I use a script to keep my dev setup updated since it has many parts.

I don't see us adding anything baked in so I'm closing this.
