### ISSUE TITLE
PlugInstall parallel install on Neovim Windows does nothing

### ISSUE THREAD

**Issue by zovt** [junegunn/vim-plug#414]
Issuing the PlugInstall command with more than one plugin name has no effect

**Comment by starcraftman** [comment]
@zovt Hi, getting around to this. To be clear from the outset, since it is experimental no promises.

I installed neovim, then neovim-qt following [instructions ](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows). I then used my own vimrc and everything seems to be working fine. Note, the parallel installer is disabled on windows nvim at this time so you should only get the single threaded installer. Are you saying the VimL installer is broken?

I used these [artifacts](https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw/job/qkxpyu7y6efh01sb/artifacts)

**Comment by fobbyal** [comment]
I am actually experiencing the same thing here.. not sure what is going on.. here are the details. And the problem seems to be outside of the nvim installation folders.

I have 2 computers one at home and one at work.
One of them don't work. (doesn't install any plugin if more than 1 is declared) The other works perfectly fine.

I copied the exact settings, binary and any file related to nvim that i know of from one to the other.. and still it can only install 1 Plugin.

Copied items
1. neovim install folder
2. configuration folder $XDG_CONFIG_HOME folder
3. neovim-qt folder.. 

Not sure what is going on here.. Just reporting this weird bug for now.

**Comment by fobbyal** [comment]
I've produced the issue on my machine. It has to do with enabling python3 nvim client.. I uninstalled python3 as i remembered that it was the last things i did before vim-plug broke. Vim Plug started working perfectly after that. @zovt Do you have python3 enabled? `:echo has("python3")` returns 1. Just want to make sure we have the same problem

**Comment by junegunn** [comment]
@starcraftman 

> the parallel installer is disabled on windows nvim

It doesn't seem so.

```vim
" s:nvim is false on windows
let s:nvim = has('nvim') && exists('*jobwait') && !s:is_win

" So...
let python = (has('python') || has('python3')) && (!s:nvim || has('vim_starting'))
```

Since I don't have a Window dev environment, I can't be sure if we can easily make the python installer work on Windows neovim. If that's not the case, we'll have to adjust the condition for some time.

Until we fix it, users can force single-threaded installer by `:PlugInstall1` or `:PlugUpdate1`, or setting `g:plug_threads` to 1.

**Comment by joshuatee** [comment]
this is not an issues just with neovim. happens using the "normal" Vim (again on windows)

**Comment by junegunn** [comment]
@joshuatee You might want to take a look at https://github.com/junegunn/vim-plug/wiki/requirements#platform-installation

**Comment by LER0ever** [comment]
Same here with GVim 8.0 (+job). `:PlugInstall` and `:PlugUpdate` appear to be single-threaded. (NeoVim on Windows works fine by the way)

**Comment by janlazo** [comment]
Does it appear single-threaded because of `system` opening a minimized cmd.exe terminal?

**Comment by Herz3h** [comment]
I had the issue where it didn't install anything, but it was because python3 was not found (it didn't tell me that was the issue, just ran a CheckHealth)

**Comment by janlazo** [comment]
Is this still happening on master?

**Comment by janlazo** [comment]
Please close if ticket is resolved or invalid on master.
