### ISSUE TITLE
Relax plugin URL checking

### ISSUE THREAD

**Issue by jwhitley** [junegunn/vim-plug#415]
As has been reported previously in #346, a writable GitHub URL causes an error during `:PlugUpdate`.  e.g. with the following plugin declaration:

```
Plug      'jwhitley/Vagrantfile.vim'
```

And the local remote for `jwhitley/mxml.vim` modified to be writable, the following error occurs:

```
x mxml.vim:
    Invalid URI: git@github.com:jwhitley/mxml.vim.git
    Expected:    https://github.com/jwhitley/mxml.vim.git
    PlugClean required.
```

In my case, I specifically do not want to force the writable URL (ala `Plug 'git@github.com...`).  My rcfiles are all version controlled, and may be installed on systems (VMs, etc.) where they do not have access to ssh keys needed for a writable URL.  Setting `g:plug_url_format` is also not a solution for me, for the same reason.

It seems that a simple solution would be to add an additional list of URL formats used only for validation:

```
let g:plug_extra_url_formats = ['git@github.com:%s.git']
```

If an URL matches `g:plug_url_format` or any of the formats in `g:plug_extra_url_formats`, then URL validation passes.

**Comment by junegunn** [comment]
- I think this is a corner case and I doubt there are many number of users who
  would benefit from the addition. You might have noticed that adding a new
  option or feature is usually the last thing we do to keep vim-plug simple
  and small.
- You can consider setting the URL conditionally, e.g. depending on
  `has('mac')`, `system('hostname')`, or some env variable. I also use my vim
  configuration across different platforms, but since I only work on Vim
  plugins on OS X, this approach works for me.
- HTTPS URLs are also writable. And it's possible to avoid username/password
  prompt: https://help.github.com/articles/caching-your-github-password-in-git/
  It also does not require SSH keys.

**Comment by starcraftman** [comment]
Just as a simple follow up to @junegunn 's second point, you could use a simple file check like this if your main issue is wanting to alternate between developing a plugin and using it on other machines.

```viml
" You could use any path, and if more than one plugin simply wrap in a for block.
if glob('~/programming/mxml.vim') != ''
  Plug '~/programming/mxml.vim')
else
  Plug 'jwhitley/mxml.vim'
endif
```

**Comment by jwhitley** [comment]
> You might have noticed that adding a new option or feature is usually the last thing we do to keep vim-plug simple and small.

Thanks for the detailed response.  I agree with the above policy in general, and that's probably reason enough to close this.  I will offer just one defense for this particular case: transparent handling of public and private repos for shorthand repo names reduces the hurdles for newer vim users when they start working on their own plugins, or even just tweaking forked upstream plugins.

The second option combined with a block that handles just the repos I own is probably the most relevant to my case, but it does imply a wholesale policy change for my plugin handling.  I'll think on it a bit.

I'll also consider the third option, but I rather like that SSH keys are revocable service-side should the need ever arise.

**Comment by liuyehcf** [comment]
Juse Comment out the following line

```vim
" raise InvalidURI(msg)
```
