### ISSUE TITLE
GVim and vimrc portable

### ISSUE THREAD

**Issue by egra-tl** [junegunn/vim-plug#438]
Hello, I am an amateur on using an editor like Vim. I have tried to find programs like GVim that would be portable from a Windows PC (e.g F:/) however after using the instructions given in the requirements, it was not clear. The challenge I got was after trying manual download of plug.vim, I could never use the md ~/vimfiles/autoload properly, the command to load the .vim plugin from curl. I am confused if it is possible to copy a GVim to a portable, and after using a _vimrc, it was constantly confused on by User/~ profile from a default installation. As I said earlier, I am only at amateur level, the vimrc I tried to use is below.

One of _vimrc is from a default load with no plug reference. The other is a ~/.vimrc or _vimrc that was edited, and it is labeled with a 2. Thankyou very much.

------------------------------
[_vimrc(2).txt](https://github.com/junegunn/vim-plug/files/159591/_vimrc.2.txt)
[_vimrc.txt](https://github.com/junegunn/vim-plug/files/159592/_vimrc.txt)

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ x] GVim
    - [ ] Neovim

**Comment by starcraftman** [comment]
@egra-tl The md command will only work on a powershell. I assume that means you are stuck with cmd.exe because powershell is not installed? There are several ways to get it:
- Just save plug.vim file to your computer and manually make ~/vimfiles/autoload. On Windows that path is C:\Users\username\vimfiles\autoload. Then move the plug.vim file into there. 
- Install native Windows build of curl and use that after making above directories.
- Use python bindings to pull the file and create dirs.

I made my own vimrc portable and automated the bootstrapping of plug, but it is a bit complex if you are just learning how to use vim. I'd suggest sticking to simple stuff as you learn, if you are interested in VimL see the excellent [learn vimscript](http://learnvimscriptthehardway.stevelosh.com/) site.

**Comment by yous** [comment]
You can also check out my [vimrc](https://github.com/yous/dotfiles/blob/e6f1e71b6106f6953874c6b81f0753663f901578/vimrc#L30-L81). It tries to resolve the path of `vimfiles` from `&rtp`, and then download `plug.vim` via git command. As vim-plug requires git, it should work. After downloading succeeds, it tries to install all plugins and then quit by `autocmd VimEnter * PlugInstall | quit`. You may want to remove `| quit` from that line. Though it's a bit complicated, I think you can get some hints from it.

**Comment by starcraftman** [comment]
@yous Thanks for contributing another acceptable solution. I'm not leaving this open any longer, either of our vimrcs are acceptable methods to resolve the original problem.
