### ISSUE TITLE
Suggesting group plugins by "for"

### ISSUE THREAD

**Issue by verzil** [junegunn/vim-plug#477]
Just want to make a suggestion that we can group plugins based on they are for. many people have multiple plugin for a specific filetype. It would be nicer if they could wrap that into a json, and group the plugins instead of calling "for" for each plugin.

**Comment by junegunn** [comment]
I believe you can do what you want with some vim scripting. Any specific syntax you have in mind?

**Comment by verzil** [comment]
basically i was thinking passing it in like how we specify a plugin
`plug#for("java")`
`plug .... java plugins here
`plug#for("done")

you mind let me try to implement that?

**Comment by junegunn** [comment]
I see, but I don't think it's something we want. The selling point of vim-plug has been that it's small, devoid of a bunch of auxiliary features that only a subset of users need, so you can grasp it very quickly and be done with it without the nagging feeling that you are missing out something.

What you're proposing can be achieved with an external helper command.

```vim
function! s:plug_with_default(...)
  Plug a:1, extend(get(g:, 'plug_opts', {}), get(a:000, 1, {}))
endfunction
command! -nargs=+ MyPlug call s:plug_with_default(<args>)

let plug_opts = { 'for': 'java' }
MyPlug 'foo/bar'
MyPlug 'bar/baz'
" ...
unlet plug_opts
```

There are rooms for improvements, but you get the idea. I can even consider exporting the function for `Plug` command calls so we can redefine `Plug` command instead of having to define an extra command. I'll let you know when that happens.

**Comment by verzil** [comment]
that is exactly what i was thinking on how to implement it.
i did notice that i need to do a bit of refactoring to the source.

Thanks for replying. :+1:

**Comment by junegunn** [comment]
I decided to export the underlying function as `plug#`, so now you can redefine `Plug` command like follows:

```vim
function! s:plug_with_default(...)
  call plug#(a:1, extend(get(g:, 'plug_opts', {}), get(a:000, 1, {})))
endfunction
command! -nargs=+ Plug call s:plug_with_default(<args>)
```
