### ISSUE TITLE
Unable to lazy load CtrlP

### ISSUE THREAD

**Issue by kshenoy** [junegunn/vim-plug#488]
I see that you are lazy loading vim-commentary using:

    Plug  'tpope/vim-commentary', {'on': '<Plug>Commentary'}
    map  gc  <Plug>Commentary
    nmap gcc <Plug>CommentaryLine

I tried the same with CtrlP but it doesn't work.

I created some plugs first so that instead of having to specify all the commands with `on`, I can say

    Plug  'ctrlpvim/ctrlp.vim', {'on': '<Plug>CtrlP'}

    nnoremap <silent> <Plug>CtrlPDefault     :CtrlP<CR>
    nnoremap <silent> <Plug>CtrlPMixed       :CtrlPMixed<CR>
    nnoremap <silent> <Plug>CtrlPMRU         :CtrlPMRU<CR>

    nmap <silent> <Space>f       <Plug>CtrlPDefault
    nmap <silent> <Space>m       <Plug>CtrlPMixed
    nmap <silent> <Space>r       <Plug>CtrlPMRU

What am I missing here?

------------------------------

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 12 2016 11:29:40)
Included patches: 1-1724
Huge version with GTK2 GUI.  Features included (+) or not (-):
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Lazy loading on `<Plug>` mapping is designed to work with the mappings that are provided by the plugin.

- `Plug  'tpope/vim-commentary', {'on': '<Plug>Commentary'}`
    - vim-plug sets up `<Plug>Commentary` mapping that will
        1. load the plugin
        2. and re-trigger the key
    - `gcc` -> `<Plug>CommentaryLine` -> `<Plug>Commentary` (by vim-plug) and `Line`
        - `<Plug>Commentary` part causes vim-plug to load the plugin
        - Then vim-plug refeeds the sequence which is then combined with `Line`
        - `<Plug>CommentaryLine` -> triggers the mapping from the loaded plugin

Likewise with `Plug  'ctrlpvim/ctrlp.vim', {'on': '<Plug>CtrlP'}`, vim-plug sets up `<Plug>CtrlP` mapping. (There's currently a subtle issue where vim-plug skips doing it on `plug#end()` if there's already a mapping that shares the prefix, which can be fixed by replacing `mapcheck()` with `maparg()`, but even if we address the issue, your configuration will not work so let's leave it out of the discussion for the moment)

And it goes, `<Space>f` -> `<Plug>CtrlPDefault` -> `:CtrlP<CR>` -> `E492: Not an editor command: CtrlP`. vim-plug has no chance to chime in.

How about using command-based loading instead? It's simpler and it just works.

```vim
Plug  'ctrlpvim/ctrlp.vim', {'on': ['CtrlP', 'CtrlPMixed', 'CtrlPMRU']}

nnoremap <silent> <Space>f :CtrlP<CR>
nnoremap <silent> <Space>m :CtrlPMixed<CR>
nnoremap <silent> <Space>r :CtrlPMRU<CR>
```

**Comment by kshenoy** [comment]
> Lazy loading on <Plug> mapping is designed to work with the mappings that are provided by the plugin.

It's interesting that you're hooking into only the `<Plug>`s provided by the plugin. I thought you were hooking into any `<Plug>`s that shared the same name.

> How about using command-based loading instead? It's simpler and it just works.

Yes, I was trying to take what I thought was the easier path, by not having to specify every command that's used. But it's not a big deal since it's a 1 time thing.

Let's say, I'm using CtrlP and ctrlp-py-matcher so I do the following:

    Plug 'ctrlpvim/ctrlp.vim', {'on': ['CtrlP', 'CtrlPMixed', 'CtrlPMRU']}
    Plug 'FelikZ/ctrlp-py-matcher'

Since I wouldn't want the matcher to get sourced on startup, is there a way to delay it till CtrlP gets sourced?

**Comment by junegunn** [comment]
We could probably come up with a way to do that, but [the plugin only has autoload directory](https://github.com/FelikZ/ctrlp-py-matcher) which means that it's not loaded until you use it, so there's no point.
