### ISSUE TITLE
Shallow clones of submodules

### ISSUE THREAD

**Issue by RubenVerborgh** [junegunn/vim-plug#515]
- Type:
  - [ ] Bug
  - [X] Enhancement
  - [ ] Feature Request
  - [ ] Question
- OS:
  - [X] All/Other
  - [ ] Linux
  - [ ] OS X
  - [ ] Windows
- Vim:
  - [X] Terminal Vim
  - [X] GVim
  - [X] Neovim

Submodules are currently cloned fully, even if the shallow option is set. Respecting the shallow option for submodules would speed up updates.

**Comment by vyp** [comment]
But how to know the depth though?

**Comment by vheon** [comment]
IIRC this was proposed in the past but for backward compatibility reasons (I think that @junegunn, as others, works with some OS that don't have enough recent version of git by default) and since we're basically just talking about YouCompleteMe there are some concern to complicate the code to handle this just for one plugin :/

**Comment by BohrShaw** [comment]
From http://stackoverflow.com/a/38895397/1297064:

> since Git 2.10+ (Q3 2016), you will be able to do a regular clone... and still benefit from shallow clone for submodules.
> All you need to do is record that configuration in your `.gitmodules`:

>     git config -f .gitmodules submodule.<name>.shallow true

The responsibility for managing shallow submodules would then better be taken by the plugin author.
