### ISSUE TITLE
Proper order for dependencies and conditionals? (Suggestion for FAQ or README)

### ISSUE THREAD

**Issue by leblancfg** [junegunn/vim-plug#544]
When using both conditional loads and dependencies on the same line, it is not clear from the readme or wiki whether to use:

`Plug 'jceb/vim-orgmode', { 'for': 'org' } | Plug 'tpope/vim-speeddating' | Plug 'mattn/calendar-vim'`

or

`Plug 'jceb/vim-orgmode' | Plug 'tpope/vim-speeddating' | Plug 'mattn/calendar-vim' , { 'for': 'org' }`

or

`Plug 'jceb/vim-orgmode' , { 'for': 'org' } | Plug 'tpope/vim-speeddating' , { 'for': 'org' } | Plug 'mattn/calendar-vim' , { 'for': 'org' }`

I believe the first one should be used, but it might be valuable to let the users know which.

Thanks again for an amazing piece of work!

------------------------------

```
vim-plug v.0.9.1
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] All/Other
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks for the suggestion. But actually there is no concept of plugin dependency in vim-plug. The example simply suggests that you can write two (or more) Plug commands in a row using `|` which acts like a semi-colon in other programming languages. It's a standard Vimscript syntax. Maybe I should clarify that in the doc.

The order almost always doesn't matter. The only case the order matters is when some plugin overrides the commands or mappings from another plugin and in that case just make sure that the Plug command for the former comes after that for the latter.

```vim
Plug 'base-plugin'
Plug 'overriding-plugin'

" Or equivalently,
Plug 'base-plugin' | Plug 'overriding-plugin'
```

As for conditional loading, I always say this: you probably don't need it. A well-written Vim plugin already loads lazily and orgmode is a good example. `vim --startuptime a.log` reveals that orgmode only loads ftdetect file in a very small amount of time, and in that case applying `on` or `for` option gives you zero benefit. It only makes your vimrc more complicated. I guess you probably mentioned orgmode just as an example, but the point remains. Setting the condition before looking at `--startuptime` log is a premature optimization and in most cases you don't need it.

If you truly need to set the condition for a set of dependent plugins, you'll have to repeat the same option for each plugin, because vim-plug doesn't know about the dependency.

```vim
Plug 'a', { 'for': 'foo' } | Plug 'b', { 'for': 'foo' } | Plug 'c', { 'for': 'foo' }
```

**Comment by roryokane** [comment]
@junegunn:

> But actually there is no concept of plugin dependency in vim-plug. The example simply suggests that you can write two (or more) Plug commands in a row using | which acts like a semi-colon in other programming languages. It's a standard Vimscript syntax. Maybe I should clarify that in the doc.

Yes please, I think you should include that information that in the README. I read the example in the README while I was trying to understand the features vim-plug offers, to decide whether to use vim-plug. But README didn’t answer my question of how one would write dependencies if multiple plugins depend on the same plugin. I guessed that either of the following could be the right way:

```vim
Plug 'lib' | Plug 'useful1' | Plug 'useful2'
```

```vim
Plug 'lib' | Plug 'useful1'
Plug 'lib' | Plug 'useful2'
```

Including the information you wrote above would help people like me decide if vim-plug is the right plugin manager for our purposes without having to search for this issue. Specifically, the following information would be helpful in the README:

- `|` is simply a stylistic convention that runs a new command; vim-plug has no specific support for dependencies. This means you only need to write a `Plug` command for a dependency once.
- Ordering of plugins only matters when overriding an earlier plugin’s commands or mappings, so putting the dependency next to the plugin that depends on it or next to other plugins’ dependencies are both okay.
- In the rare case where plugins do overwrite commands or mappings, vim-plug requires you to manually reorder your plugins.
- vim-plug doesn’t have any special way of noting the dependencies of plugins so that you can figure out when a dependency can be safely deleted. If you want that information, you must write comments, like this:
    
    ```vim
    " note to self: lib is needed for the useful1 and useful2 plugins
    Plug 'lib'
    
    " other plugin declarations might be here…
    
    Plug 'useful1'
    Plug 'useful2'
    ```

**Comment by junegunn** [comment]
@roryokane Nice write up, thanks. I think I'm gonna just remove the bar example from the README page, as it only seems to serve as a source of confusion. And I'll post your summary on the wiki page.

**Comment by junegunn** [comment]
@roryokane What do you think about changing the comment as follows?

It doesn't say anything about dependencies, but it might help some users to learn about this trick and use it to (manually) express plugin dependency in their configuration.

```vim
" Multiple Plug commands can be written in a single line using | separator
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
```

**Comment by roryokane** [comment]
@junegunn I think that would be an improvement. I’d add “a” to make it grammatically correct:

```vim
" Multiple Plug commands can be written in a single line using a | separator
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
```

The README would no longer mention the word “dependencies”, which would make it harder for someone skimming the README to find out what vim-plug’s support for them is. So I guess it’s good to keep that `|` example, because it implies vim-plug’s (lack of) support for dependencies when it is read carefully.

For readers wondering about dependency support, hopefully it would be clear enough to have that implying `|` example plus an explicit explanation in the [FAQ](https://github.com/junegunn/vim-plug/wiki/faq) titled “How should I specify plugin dependencies?”. Maybe the FAQ is the page you were thinking of when you mentioned posting my summary on a wiki page.

Here’s the Markdown source of my comment so you don’t have to mark it up again:

````markdown
Yes please, I think you should include that information that in the README. I read the example in the README while I was trying to understand the features vim-plug offers, to decide whether to use vim-plug. But README didn’t answer my question of how one would write dependencies if multiple plugins depend on the same plugin. I guessed that either of the following could be the right way:

```vim
Plug 'lib' | Plug 'useful1' | Plug 'useful2'
```

```vim
Plug 'lib' | Plug 'useful1'
Plug 'lib' | Plug 'useful2'
```

Including the information you wrote above would help people like me decide if vim-plug is the right plugin manager for our purposes without having to search for this issue. Specifically, the following information would be helpful in the README:

- `|` is simply a stylistic convention that runs a new command; vim-plug has no specific support for dependencies. This means you only need to write a `Plug` command for a dependency once.
- Ordering of plugins only matters when overriding an earlier plugin’s commands or mappings, so putting the dependency next to the plugin that depends on it or next to other plugins’ dependencies are both okay.
- In the rare case where plugins do overwrite commands or mappings, vim-plug requires you to manually reorder your plugins.
- vim-plug doesn’t have any special way of noting the dependencies of plugins so that you can figure out when a dependency can be safely deleted. If you want that information, you must write comments, like this:
    
    ```vim
    " note to self: lib is needed for the useful1 and useful2 plugins
    Plug 'lib'
    
    " other plugin declarations might be here…
    
    Plug 'useful1'
    Plug 'useful2'
    ```
````

**Comment by junegunn** [comment]
@roryokane Thanks for the comment. Maybe plural form "separators" is better since we can write more than 2 statements in a row? e.g. `Plug 'foo' | Plug 'bar' | Plug 'baz'`

I added a section to the FAQ page based on your writing: https://github.com/junegunn/vim-plug/wiki/faq#managing-dependencies

**Comment by roryokane** [comment]
@junegunn Yeah, “`… using | separators`” sounds better. The FAQ section looks good.
