### ISSUE TITLE
parallel do commands

### ISSUE THREAD

**Issue by nhooyr** [junegunn/vim-plug#575]
It'd be nice if make commands to build plugins ran asynchronously instead of blocking.

------------------------------

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by vheon** [comment]
Do you mean asynchronously or in parallel? Because I don't see the advantages to build plugins asynchronously since you would not be able to use them until they have completed the build step anyway so you would be waiting. Do them in parallel could make sense but how many plugin do you have that require the build step? Is it actually worth it to do it?

**Comment by nhooyr** [comment]
Parallel is what I meant, sorry! I don't have many, but it'd just be nice to not have my screen blasted with messages from `make`.

**Comment by vheon** [comment]
And how running the build step in parallel would solve that problem? If that is what you want is to run the build step with a `job` so that you don't see the output on the screen (I think Neovim already does that when you use `:!` but I could be wrong). And if that is what you want you can do it right now using a custom function for the `do` and writing the job handling there.

**Comment by nhooyr** [comment]
I meant, as a consequence of making the do command async, I wouldn't have my screen blasted. That's not the only reason, it would also become faster. It's just a nice user experience change.

**Comment by vheon** [comment]
As I said earlier

> Is it actually worth it to do it?

The cost of doing this is to implement it for the Vim job API and Neovim job API and a mechanism to display the output, plus the cost of maintain the new code and current implementation. I'm not saying that would be a bad idea I'm just wondering if is worth it and in the end is all in @junegunn hands ;)

**Comment by junegunn** [comment]
I'm with @vheon on this.

> you would not be able to use them until they have completed the build step anyway so you would be waiting.

This is spot on, it will leave the plugins in inconsistent states, which can degrade the user experience. It should not be the default. And out of 58 plugins I have, only two are set with *optional*, not mandatory, build steps. So, let's just keep it simple.

@nhooyr 

> it'd just be nice to not have my screen blasted with messages from make.

`make > /dev/null` ?

Anyway, this is something I would do, using Neovim terminal or tmux window.

```vim
function! AsyncDo(command)
  if has('nvim')
    return printf(':tabnew | call termopen(%s) | tabprev', string(a:command))
  elseif exists('$TMUX_PANE')
    return printf('tmux new-window -d "%s"', escape(a:command, '"'))
  endif
  return a:command
endfunction

Plug 'foobar', { 'do': AsyncDo('make all') }
Plug 'barfoo', { 'do': AsyncDo('./install.py') }
```

**Comment by nhooyr** [comment]
That works well, except for when there is plugin with a git submodule update. In that case, I can't modify the command used so my screen gets blasted.
