### ISSUE TITLE
call `plug#begin()` with no argument in the example

### ISSUE THREAD

**Issue by anntzer** [junegunn/vim-plug#579]
The [example](https://github.com/junegunn/vim-plug#example) starts with a call to `plug#begin('~/.vim/plugged')`.  You already have the logic to select `${first_entry_of_rtp}/plugged` if `plug#begin` is called with no argument, so I would suggest doing so in the example, in order to make it applicable for Windows (where rtp starts with `~/vimfiles` instead) -- and I guess for neovim as well, given the comment in the example.

------------------------------

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
Thanks for the suggestion, but I actually took the opposite direction: 3e65d146ad051e6e65d5797e23d8820b35025e93

Choosing the first path in the runtimepath seemed like a nice idea at first so I suggested it in the past, but it turned out to have been a source of confusion for some users. It is possible that the user manually modifies the runtimepath before `plug#begin` and ends up with unexpected results. So I decided that we're better off not relying on the mutable global state and being explicit about the path. For using the same configuration file across different platforms, one can use something like `has()` to decide which path to use. It's obviously more verbose but I believe it's safer and should be preferred.

```vim
call plug#begin(has('win32') || has('win64') ? '...' : '...')
```
