### ISSUE TITLE
Allow glob patterns on `on`

### ISSUE THREAD

**Issue by mcchrish** [junegunn/vim-plug#585]
Possible to do glob pattern on `on`? For example, `fzf.vim` can have commands like `FzfFiles`, `FzfCommits` and so on.
The configuration would look like this:
```vim
Plug 'junegunn/fzf.vim', { 'on': 'Fzf*' }
```

------------------------------

```
:version
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCL
UDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161129-56964-dc0z4u/neovim-0.1.7/build/config -I/tmp/neovim-20161129-56964-dc0z4u/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/lo
cal/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161129-56964-dc0z4u/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161129-56964-dc0z4u/neovim-0.1.7/build/include
Compiled by mcchris@mc-mbp.local

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
It's not possible. When you specify the name of a command, vim-plug sets up a proxy command of the same name that loads the plugin which is supposed to implement the command, and rerun the command hoping that it's now properly loaded. Without an exact name, vim-plug can't define the proxy command.

More importantly, you most likely don't need it. A well-structured vim plugin should already load lazily without any help from the plugin manager. Make sure that you're tackling the right problem by breaking down the start up time of vim using `--staruptime` option. fzf.vim is especially a bad example here because it loads in less than a millisecond. There are very few cases where `on` or `for` options make much sense.
