### ISSUE TITLE
'on' to work with regular mappings

### ISSUE THREAD

**Issue by partounian** [junegunn/vim-plug#605]
Would it be possible to get 'on' to work with regular commands used in Normal mode? I noticed dein.vim has it implemented, but I am bit of a fan of your vim-plug and other vim works, so I thought I could ask.

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [X] Feature Request
    - [ ] Question

**Comment by junegunn** [comment]
You mean key sequences other that `<plug>` mappings? It's not supported, but you can implement it using `plug#load` function without difficulty, for example:

```vim
Plug 'mbbill/undotree', { 'on': [] }

function! s:load_with_keys(keys, plugin)
  execute 'unmap' a:keys
  call plug#load(a:plugin)
  return a:keys
endfunction

nnoremap <expr> gg <sid>load_with_keys('gg', 'undotree')
```

I'm currently not interested in extending vim-plug to support different types of load triggers, not because it's hard to implement, it's quite the opposite, but because I believe these things should be used sparingly with caution only when necessary. I've seen so many people waste their time tweaking their plugin configurations, even when there's no practical benefit to it. And I don't want to encourage that by providing more options.

Also see https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

**Comment by partounian** [comment]
Thank you, @junegunn I understand the purpose for using it and not to use overuse it. This plugin (tcomment_vim) just seems to add excessive load time to vim.

**Comment by junegunn** [comment]
I see, I personally use and recommend commentary.vim by tpope, because, tpope.
