### ISSUE TITLE
Open commit from PlugDiff in an external browser?

### ISSUE THREAD

**Issue by comand** [junegunn/vim-plug#609]
Right before I switched to vim-plug from neobundle, neobundle added a feature which prints a link for each updated plugin. The link takes you to a github view showing all of the commits between the version you had prior to the update, and the version after the update.

I think the PlugDiff view in vim-plug is superior to the view provided by neobundle, but I do miss being able to see what was actually updated rather than just the change log. Would it be possible to provide a command that would open a commit displayed by PlugDiff in an external browser?

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
1. Are you aware that you can press enter key or `o` on each commit line to see the diff on the preview window?
2. The default preview window is a bit small, I use the following options so that vim-plug opens in a new tab, and the preview window on the right side of the screen
```vim
let g:plug_window = '-tabnew'
let g:plug_pwindow = 'vertical rightbelow new'
```
3. If you really like to use an external browser instead of the preview window:
    - https://github.com/junegunn/vim-plug/wiki/extra#gx-to-open-github-urls-on-browser

**Comment by comand** [comment]
This is awesome -- thanks for the pointers.
