### ISSUE TITLE
Conditionally disable plugins if vim too old/missing extensions

### ISSUE THREAD

**Issue by williamsmj** [junegunn/vim-plug#621]
Is is possible to load plugins only if vim is above a certain version, or has been compiled with certain extensions?

I'd like to add
```
Plug 'maralla/completor.vim'
```
to my configuration, but [completor](https://github.com/maralla/completor.vim) requires vim 8+ compiled with python or python3, which is not true everywhere I copy my vim configuration.

I know vim-plug makes it possible to disable plugin loading for certain filetypes, etc. but I can't see an easy way to do this on properties of vim itself.

**Comment by junegunn** [comment]
It's really straightforward.

```vim
if v:version >= 800 && (has('python') || has('python3'))
  Plug 'maralla/completor.vim'
endif
```

See https://github.com/junegunn/vim-plug/wiki/faq#conditional-activation

**Comment by ryanp97** [comment]
I'm trying to get it to load a plugin if the filetype is not 'tex', but unfortunately, the following doesn't work.

```
if &filetype!='tex'
    Plug 'jiangmiao/auto-pairs'
endif
```

Any ideas on how to get this working?

**Comment by janlazo** [comment]
@ryanp97 Come up with an autocmd to trick `AutoPairsTryInit()`. Request @jiangmiao to add an `augroup` for the plugin to make it easier to check the `augroup` and `autocmd` load order. vim-plug can't help you here because conditional activation is meant for global checks (ie. `v:version`, `has('python')`) between `plug#begin()` and `plug#end()`, not `&filetype` and other buffer-local properties.
