### ISSUE TITLE
Vim-Plug error with nerdTree autocommand example

### ISSUE THREAD

**Issue by soulomoon** [junegunn/vim-plug#660]
Installing nerdTree with vim-plug
[s:lod_cmd](https://github.com/junegunn/vim-plug/blob/449b4f1ed6084f81a1d0c2c1136cd242ec938625/plug.vim#L509) throw an error while executing
```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
```
in vimrc when starting up vim

The details of the problem can be found
[Here](https://github.com/scrooloose/nerdtree/pull/725)

**Comment by junegunn** [comment]
In this particular case, `exec 'NERDTree'` will fix the issue, but just don't use `on` option.

https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

`on` sets up a proxy command of the same name, but without `-bar` option, so in this case, it doesn't recognize the following `| endif` and fails.

vim-plug cannot confidently apply `-bar` to the proxy command as it has other side-effects. Fixes something, breaks another.

**Comment by lifecrisis** [comment]
@junegunn, does your suggestion for @soulomoon fix his problem (i.e., not using the `on` option)? Since the code in our README is correct, I'd rather not change it to accommodate this particular case. It seems more like an issue of using vim-plug in the recommended way.

@soulomoon, did @junegunn fix your error?

**Comment by junegunn** [comment]
Yes, it should.

**Comment by soulomoon** [comment]
@junegunn @lifecrisis 
Yes, removing the `on`  option fix the problem
