### ISSUE TITLE
Command to load a plugin

### ISSUE THREAD

**Issue by blueyed** [junegunn/vim-plug#674]
It would be nice to have a command (with completion) for loading a plugin, basically wrapping `plug#load()` and offering completion where non-loaded plugins are offered.

**Comment by junegunn** [comment]
I'm not sure if it's a good idea to add features that may give the impression to the users that lazy-loading (`on` or `for`) is something they should use more, when I think they shouldn't.

We know that well-designed plugins have most of their code in `autoload` directory and already take trivial time to load, and lazy-loading facilities provided by plugin mangers are fragile workarounds that are not guaranteed to work.

That said, we could extend `g:plugs` so that it contains information whether a plugin is loaded or not, and the users can implement custom completion based on it.

```vim
function! s:plug_names(...)
  return sort(filter(keys(g:plugs), 'stridx(v:val, a:1) == 0 && !g:plugs[v:val].loaded'))
endfunction

command! -nargs=+ -bar -complete=customlist,s:plug_names PlugLoad call plug#load([<f-args>])
```

**Comment by hiberabyss** [comment]
Hi @junegunn , 
Seems `g:plugs` did not support  `.loaded` currently, is there any plan to support it?

Thanks!

**Comment by junegunn** [comment]
No plan. Actually, I'm not really interested in adding or extending anything related to on-demand loading facility, as I no longer think it's a good idea. If you really need the feature for some reason, this is something you can try.

```vim
function! s:plug_loaded(spec)
  let rtp = join(filter([a:spec.dir, get(a:spec, 'rtp', '')], 'len(v:val)'), '/')
  return stridx(&rtp, rtp) >= 0 && isdirectory(rtp)
endfunction

" Plugins installed but not loaded
echo keys(filter(copy(g:plugs), { k, v -> !s:plug_loaded(v) }))
```
