### ISSUE TITLE
Abitrarily changes user's formatting configuration

### ISSUE THREAD

**Issue by salamander2** [junegunn/vim-plug#703]
**Problem:**

This plugin does other behinds the scenes stuff that it should not be doing. It arbitrarily imposes the author's idea of how my VIM formatting should be setup. This program is intended to manage plugins. It is intended to be clean, simple, elegant and do one thing and do it very well. Yet is screws up my formatting for no good reason. This plugin should not be doing on-line banking, checking my hard drive for errors, _nor formatting my text according to the author's beliefs how text should be formatted._ **This is broken and needs to be fixed.** 

**Temporary Solution:** I had to switch to a GUI editor, then uninstall vim-plug in order to do my work until I figured out what it was doing and tried to prevent this unintended behaviour.

**Example:**
Pasting into an empty file called "stuff":
```
/* This is a simple program that will not be pasted into VIM now that I have plugins!
 * How annoying!
 * And here is another line starting with *
 * another line
 * and another! */
import java.util.*;

public class SimpleProgram {

    public static void main(String[] args) {
            //Hey, let's say hello!
            System.out.println("Hello peeps");

            System.out.println("Wazzup?");
    }   

}
```

And here's when I paste exactly the same code into "stuff.java"

```
/* This is a simple program that will not be pasted into VIM now that I have plugins!
 *  * How annoying!
 *   * And here is another line starting with *
 *    * another line
 *     * and another! */
import java.util.*;

public class SimpleProgram {

            public static void main(String[] args) {
                                    //Hey, let's say hello!
                                    //              System.out.println("Hello peeps");
                                    //  
                                    //                              System.out.println("Wazzup?");
                                    //                                      }
                                    //  
                                    //                                      }
                                    //               
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Pointers:
- https://github.com/junegunn/vim-plug#usage
- `:help ft-vim-indent`
- `:help 'paste'`

**Comment by salamander2** [comment]
The problem is: why is a plugin whose sole purpose is to manage plugins changing the formatting of my data? This is blatant feature creep. It really doesn't make sense to me. Why would you assume that everyone wants the same formatting you do when they download your plugin? It's like Microsoft assuming that by downloading Windows 10, you agree to send information back to MS, unless you specifically take the extra steps to disable it.

Do one thing and do it well. If you want a plugin that changes the formatting of vim, then write a completely separate plugin for that purpose. Does this make sense?

**Comment by nfischer** [comment]
I believe this could be due to `filetype plugin indent on` (see [docs](https://github.com/junegunn/vim-plug#usage)). @salamander2 have you tried the recommendation there?

**Comment by junegunn** [comment]
I gave you enough pointers to learn what's going on, but you don't seem to have read any of the links. vim-plug does not change the formatting of your data, it only enables filetype-specific auto indentation mode of Vim that many plugins require (other plugin managers tell you to [do it manually](https://github.com/VundleVim/Vundle.vim#quick-start) saying it's required, but vim-plug does that for you by default, while providing the instruction for turning it off when it's not desirable, it's a matter of design choice. But since you don't know about the option, don't know if you want or don't want the option, you should have run into the same problem regardless.

When you "paste" some text, Vim thinks you're typing it by hand, so it performs auto-indentation as the text comes in. There are ways to workaround the problem; `'paste'` option is one, setting system clipboard as the default register in Vim is another.

https://stackoverflow.com/questions/2514445/turning-off-auto-indent-when-pasting-text-into-vim
