### ISSUE TITLE
:UpdatePlugins blocks input

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [junegunn/vim-plug#709]
I use a shell-alias like the following to update plugins, after installing something new:

    nvim +UpdatePlugins +only

Unfortunately, further commands (like that `:only`) fail to evaluate until *after* `:UpdatePlugins` is completely finished.

This isn't a huge deal, or anything, but I thought it might be worth mentioning. `(=`

------------------------------

```
NVIM v0.2.1-331-g6650588c                                                                                  
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_H
AS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough
 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170614-52857-dmx2ql/build/con
fig -I/tmp/neovim-20170614-52857-dmx2ql/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/
local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode-beta.app/Contents/Developer/Pl
atforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20170614-52857-dmx2ql/build/src/nvim/auto -I/tmp/neovi
m-20170614-52857-dmx2ql/build/include
Compiled by ec@Fannie.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-6650588/share/nvim"
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
You mean `:PlugUpdate`, right? There's no `UpdatePlugins`.

The blocking behavior is intentional, as we have many users doing updates in their scripts, i.e.

```vim
vim +PlugUpdate +qa
```

If `PlugUpdate` doesn't block, Vim will quit immediately before plugins are updated. See #104. 

Since `PlugUpdate` now takes `--sync` flag, one can write `vim +'PlugUpdate --sync' +qa` even if we don't force this, but I'd rather not surprise users by making a breaking change. And I'm not really into the idea of introducing another `--async` option that is only useful in this niche use case.

**Comment by ELLIOTTCABLE** [comment]
Sounds good! Isn't really a deal-breaker in any case.
