### ISSUE TITLE
Publish Homebrew formula

### ISSUE THREAD

**Issue by mcandre** [junegunn/vim-plug#795]
VimPlug is awesome! Could we get a formula published to the Homebrew package manager, to make it easier to install?

**Comment by mcandre** [comment]
Copying and pasting arbitrary text blobs is the opposite of automation. Copying and pasting arbitrary text is accident-prone, requires advanced user knowledge, and actually presents security risks. Better to provide a tested formula.

**Comment by ziweiwu** [comment]
That's a good idea.

**Comment by junegunn** [comment]
Homebrew will not install plug.vim in your `.vim` directory, so you'll have to put an extra line in your Vim configuration. I don't like it because it's an extra step that only applies to a subset of vim-plug users and it may confuse the others.

The above command is just for downloading a single file from GitHub via secure SSL connection (_"Download plug.vim and put it in the "autoload" directory."_ from README page). You don't have to use the exact command.

So I don't see much point of using Homebrew, but you can write a formula and send a pull request to homebrew-core if you want.

**Comment by ziweiwu** [comment]
Make sense, home brew is bit redundant.

**Comment by CaraJDonnelly** [comment]
I would also like a homebrew formula for vim-plug.

Encouraging people to copy-paste complicated commands into their terminals is encouraging unsafe behavior.

**Comment by windware-ono** [comment]
> So I don't see much point of using Homebrew

People want a unified package management and not keep 1 software under 'git' command which also makes updating harder than just hitting the 'update' command on homebrew.

Homebrew is not just for Mac but there's also Linuxbrew.

**Comment by junegunn** [comment]
@CaraJDonnelly @windware-ono If you really want it, you can make a Homebrew formula for vim-plug and send a pull request to homebrew-core. I don't need one so I have no plan to work on it.
