### ISSUE TITLE
Parallel installer on Windows GVim does not show progress

### ISSUE THREAD

**Issue by saaguero** [junegunn/vim-plug#81]
Could be this because of this issue? https://github.com/junegunn/vim-plug/issues/4

I mean, it works perfectly, but I don't have any feedback about the progress except for many consoles being opened, I supposed that each one represents a git process cloning the corresponding plugin.

If that is the case, have you tried any solution? Or something that's blocking the implementation?

**Comment by starcraftman** [comment]
@junegunn I ran into this too, annoyingly. I reported it to the vim_dev list (1) because the problem seems to lie directly with GVim rather than something in this plugins code. Seems that with the Windows version, when you are inside an embedded language you can't call redraw. Ever. I suspect the main UI loop may be blocked waiting for command to finish? 

Due to this, I'm not certain what I'm going to do for Windows. Debating whether to just leave it disabled like ruby since its so poor to see GVim freeze until command unblocks.

1) https://groups.google.com/forum/#!topic/vim_dev/Pmisv__GAFo

**Comment by junegunn** [comment]
@starcraftman Yeah, I've been considering disabling parallel installer on Windows altogehter because the experience is really horrible and unstable. It's perfectly fine for me if you decide to give up supporting Windows on your python implementation.
