### ISSUE TITLE
manage manually installed plugin that is also a git repo

### ISSUE THREAD

**Issue by xarthurx** [junegunn/vim-plug#842]
So I'm developing my own vim plugin that needs modification of the file quite often.
The plugin is a git repo which means there's a `.git` folder inside.

I manually pulled it to the vim plugin folder so that I don't need to push it to github and updated with `vim-plug` every time I want to do some test.

```
Plug './vim-xxx'
```

However, the current issue is that when I update plugins, this special plugin will always make `vim-plug` complain:

```
x vim-xxx:
    Invalid URI: https://github.com/xarthurx/vim-xxx
    Expected:    https://git::@github.com/./vim-xxx.git
    PlugClean required.
```

Is there a way to manage a plugin but skip it from update action?

Thanks.

------------------------------

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
vim-plug currently only recognizes spec strings start with either `~` or `/` as local plugins. So something like `Plug '~/my-plugins/vim-xxx'` should do. (`Plug './vim-xxx'` is probably not a good idea, because it depends on the current working directory.)

Or instead of relying on vim-plug, you can simply add the directory to `&rtp` after `plug#end()` call.

```vim
set rtp+=./vim-xxx
```
