### ISSUE TITLE
[Feature Request] Unconditional post-update hook

### ISSUE THREAD

**Issue by idanarye** [junegunn/vim-plug#859]
Current post-update hooks are plugin-bound, and only run if a specific plugin was updated or installed. But it can be useful to have a hook that runs even if no plugin was installed.

My main usecase is [coc.nvim](https://github.com/neoclide/coc.nvim), which has its own subplugin management system (because its plugins are Node.js modules). I'd like to be able to run `:CocUpdate` after `:PlugUpdate` is finished, whether CoC was updated or not (CoC gets updated daily, but it does not seem right to rely on that...)

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question

**Comment by junegunn** [comment]
> have a hook that runs even if no plugin was installed

If you provide `--sync` flag to `:PlugUpdate` or `:PlugInstall`, it blocks until completion. So you can just write:

```vim
:PlugUpdate --sync | CocUpdate
```

**Comment by loganswartz** [comment]
Would it be possible for this FR to be reconsidered? I use a small plugin to show the number of available plugin updates in the statusline, and it works by updating a global variable with the number of updates available. My statusline calls a small function to read that global variable, because calling the full `CheckForUpdates` function that updates that variable every time would be needlessly expensive. 

Having an indiscriminate, global post-update hook would be perfect for me in this case, because I could automatically call the `CheckForUpdates` function whenever `PlugUpdate` or `PlugInstall` is called to update the visible number of updates. Yes, as you noted, I could just use `:PlugUpdate --sync | CheckForUpdates`, or put a post-install hook after every single plugin I have, or even create a wrapper function like `RunUpdates` as an alias for `:PlugUpdate --sync | CheckForUpdates`, but all of those solutions are less than ideal. If I'm always going to run a certain command after running `PlugUpdate`, manually typing it is just an extra waste of time, I'd prefer to simply be able to use `PlugUpdate` by itself instead of a janky wrapper function like mentioned above to get that functionality. If it was seen as beneficial to allow for individual post-install hooks, what's not to say there aren't valid uses for a global post-install hook?

**Comment by junegunn** [comment]
While it's trivial to add some code to trigger a `User` autocmd, I'd really like to keep the feature set of vim-plug as small as possible.

I don't understand why you say

> manually typing it is just an extra waste of time

when you can

> create a wrapper function like RunUpdates as an alias for :PlugUpdate --sync | CheckForUpdates

You can even save a few more keystrokes that way.

```vim
command! -nargs=* PU PlugUpdate --sync | echom 'foo'
```

What is so wrong about defining a shortcut? Don't we all use a bunch of shell aliases and functions every day?

> If it was seen as beneficial to allow for individual post-install hooks

A post-update hook for a plugin is triggered only when the plugin is updated with some actual changes. It isn't easy to replicate the logic outside of vim-plug.

**Comment by loganswartz** [comment]
> What is so wrong about defining a shortcut? Don't we all use a bunch of shell aliases and functions every day?

I guess I can't really complain about the extra time spent typing since you're right, I could easily condense it down to just a character or two and save myself even more time.

> A post-update hook for a plugin is triggered only when the plugin is updated with some actual changes. It isn't easy to replicate the logic outside of vim-plug.

Another fair point, can't argue with that.

I guess my desire for an indiscriminate post-install hook comes from wanting to be able to add additional custom functionality to the "vanilla" `PlugUpdate`, and for me, a true global post-install hook would feel less tacked on than simply doing an alias. Then again, I guess personal preference on methodology isn't a very compelling reason to justify implementing a semi-redundant feature, and your reasoning makes sense 👍
