### ISSUE TITLE
Plugins not downloaded - windows

### ISSUE THREAD

**Issue by AndiLeni** [junegunn/vim-plug#868]
Hello,
I tried to install coc via vim-plug, but it seems like vim does not download anything.
When I run ``:PlugInstall`` the following lines appear:
````
Updated. Elapsed time: 0.224181 sec.
[x]

- Finishing ... Done!
x coc.nvim:
    OK
````
But the folder which I set in my _vimrc for plug is still empty. 

Here is my vim file:
````
colorscheme molokai
set guioptions-=T
set guifont=Consolas:h12


call plug#begin('C:\vimplugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

set hidden

set textwidth=70

let g:coc_force_debug = 1
let g:coc_node_path = 'C:\Program Files\nodejs'

source $VIMRUNTIME/mswin.vim
behave mswin
````

Thanks in advance
Andi

------------------------------

```

```
![grafik](https://user-images.githubusercontent.com/13385771/62832303-704a2100-bc2c-11e9-84f8-e75bb6ad2bb5.png)

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
I assume you copied coc.nvim config from https://github.com/neoclide/coc.nvim#table-of-contents but you need the `do` hook to run the install script. It didn't work for me when I tried so I rolled my own (see https://github.com/janlazo/dotvim8/blob/0e5d2d83833311b8d99e246b3fea7ff19863deda/shared.vim#L658-L678)

**Comment by AndiLeni** [comment]
@janlazo Thanks for your answer.

**Comment by janlazo** [comment]
Note: `%USERPROFILE%` is cmd.exe environment variable named `USERPROFILE`. Verify with `set USERPROFILE`.

Assuming you have `%USERPROFILE%\vimfiles\vimrc` so that you can store vim plugins in `%USERPROFILE%\vimfiles\plugged`, then, in your vimrc, put `call plug#begin(expand('<sfile>':p:h) . '/plugged')` instead of `call plug#begin('C:\vimplugged')`.

As for coc.nvim, its vim-plug config previously had `'do': 'sh ./install.sh'` (non-Windows) or `'do': '.\install.cmd'` (Windows) but I can't find it now. I didn't work for me so my `do` hook does the equivalent of the bundled platform-specific shell scripts by downloading the archive containing the javascript bundle, decompressing the archive, and move the javascript bundle to the required directory so that coc.nvim Vim plugin will work.

I used for curl + tar because my config is cross-platform but you can use powershell and the built-in .Net class for zip archives to download and decompress the zip archive. Check the coc.nvim shell scripts yourself.

I use `coc.nvim` on Neovim 0.4 only so you're on your own to figure out the min. Vim version to make coc.nvim work. You need node.js and npm (or yarn).

**Comment by janlazo** [comment]
I updated coc.nvim on my vimrc and used the recommended install instructions (release branch, git tags) instead of my workaround in https://github.com/junegunn/vim-plug/issues/868#issuecomment-520268401. No errors.

Problem can be narrowed down to the following lines of the vimrc:

```vim
" user permission
call plug#begin('C:\vimplugged')

" no tag to lock down the commit
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" This shouldn't be necessary if nodejs is installed correctly and node, npm, yarn are available in %PATH%
let g:coc_node_path = 'C:\Program Files\nodejs'
```
