### ISSUE TITLE
Error: Parameter format incorrect

### ISSUE THREAD

**Issue by eduardoarandah** [junegunn/vim-plug#874]
I've been using this plugin for a while, and all of a sudden, this happened:

![imagen](https://user-images.githubusercontent.com/4065733/63988910-f4f9c380-caa3-11e9-8d17-a956b7e15c86.png)

I removed almost all lines, removed vim-plug and no success, from now on, plugins shows error when `PlugInstall`

I tried `PlugUpgrade` and gives me this:

![imagen](https://user-images.githubusercontent.com/4065733/63988985-3d18e600-caa4-11e9-8f71-048099472f4a.png)

Gvim 8, windows 10, this happened all of a sudden, without doing anything special.... any ideas?

**Comment by junegunn** [comment]
@janlazo Any idea what's going on here?

**Comment by janlazo** [comment]
Each batchfile runs `chcp 65001` for (utf8) and may run a shell command directly instead of wrapping it in a batchfile since https://github.com/junegunn/vim-plug/commit/8a44109329757e29c4956162e3353df367ecdb71. Either one causes the problem. If it's the latter, then https://github.com/junegunn/vim-plug/issues/690 can't be fixed because a batchfile is always required for correctness.

@eduardoarandah Does `set encoding=utf-8` have any effect?

**Comment by eduardoarandah** [comment]
@janlazo I've always had this in my .vimrc:

```
set encoding=UTF-8
set fileencoding=utf-8 
```

maybe commenting the part of "deleting the batch file" after executing it and then checking out what is going on inside the file might bring some light to the issue?

**Comment by janlazo** [comment]
#886 is merged.
