### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by 178me** [junegunn/vim-plug#899]
Explain the problem here ...

------------------------------

```
curl does not connect to the server Error: curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection timed out
```

- Type:
    - [ y] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [y] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [y] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
https://github.blog/2018-02-01-crypto-removal-notice/#known-incompatible-clients
Upgrade your environment to use TLS 1.2+

**Comment by lilydjwg** [comment]
No, this isn't necessarily caused by TLS issues. As known elsewhere, the poster is lived in mainland China. And recently raw.githubusercontent.com is blocked by China (DNS pollution), causing timeouts or certificate mismatch or connection refused (or anything else when connecting to a wrong IP, e.g. 127.0.0.1). This might be the cause.

**Comment by 178me** [comment]
> https://github.blog/2018-02-01-crypto-removal-notice/#known-incompatible-clients
> Upgrade your environment to use TLS 1.2+

How to update to 1.2 +, and how to view the current version
