### ISSUE TITLE
Disable plugin for specific filetype - opposite of for

### ISSUE THREAD

**Issue by danihodovic** [junegunn/vim-plug#928]
Use case: I want to enable [tmsvg/pear-tree](https://github.com/tmsvg/pear-tree) for html file types and [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs) for the rest.

Currently I need to explicit list all the filetypes I want to use autopairs for which is impractical.

Would you be open to add this feature?

**Comment by junegunn** [comment]
You should generally not rely on `for` option in that case. It wasn't built for that purpose. There is no way to "unload" a plugin once it's loaded inside Vim. So even if you set up such load conditions,

- Open an HTML file
    - pear-tree is loaded
- Open a non-HTML file
    - auto-pairs is loaded
- From now on, both plugins are in action regardless of the file type

That's obviously not what you want. You should see if the plugin provides an option or a command to disable itself.

vim-plug will not extend the on-demand loading feature because 1. it's a brittle hack that is not guaranteed to work, 2. and they are mostly not needed are people are overusing it without fully understanding the implications

- https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

But if you still want to manually control the load condition, use an autocmd as suggested below.

- https://github.com/junegunn/vim-plug/wiki/tips#loading-plugins-manually
