### ISSUE TITLE
[Feature Request] Prompting for updates if available

### ISSUE THREAD

**Issue by PezCoder** [junegunn/vim-plug#938]
#### Feature detail
I've been using VIM for more than 3 years & what I've realised is, some lazy weekend I run `:PlugUpdate` just so my dependencies are up-to date & there is hell lot of cool stuff features/fixes that has come by the time I run a command.

Since the vim-community is pretty active in pushing fixes/features for plugins, wouldn't it be great if we could know when any updates are available & can trigger it with a keystroke?

I think this behaviour is quite consistent across editors globally whether it's sublime, visual studio, eclipse etc. Would be great if we can make this happen in VIM as well.

#### Scope
- I think considering vim-plug handles the plugin installation, updating currently I'm not sure if handling prompts should be a part of it or not. But we can definitely provide something which tells a yes or no to the question `Is there any updates available for the plugins installed?` .. 

#### Contributing
- I don't have any experience with vim-script, but I would love to contribute however I can with the right guidance. Count me in & thumbs up, if you think this feature could be useful. 🤞 

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
You can find the previous discussion on the topic here: https://github.com/junegunn/vim-plug/issues/493

To sum up, we're not interested in adding the feature to vim-plug, which labels itself a "minimalist vim plugin manager". However, since vim-plug exposes its data structure as `g:plugs`, one should have no problem implementing an external notifier plugin using it. Actually, there is one already: https://github.com/semanser/vim-outdated-plugins. You might want to take a look at it.

**Comment by PezCoder** [comment]
Thank you @junegunn for taking the time & pointing me at the plugin.
I did look through the issues to see if this has been discussed, must have missed it. My bad ! 🙇
