### ISSUE TITLE
PlugClean doesn't remove removed plugins

### ISSUE THREAD

**Issue by vaklinzi** [junegunn/vim-plug#971]
First, thank you for the great project. I just love it and use it every day. My problem is that :PlugClean doesn't clean the removed plugins. Doesn't matter whether I comment them " or just delete them completely from init.vim. :PlugClean doesn't remove them from plugged folder. I do not have any errors but every time I should go to delete them by hand. 

------------------------------

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by adelin-b** [comment]
Me too, for a few weeks now it just hang and I have to delete them by hand or remove the complete vimplug cache folder.
Any steps to know how to debug this?

**Comment by janlazo** [comment]
To delete a plugin, comment out or delete the code that adds the plugin to vim-plug's list of plugins (ie. `:Plug`), close the editor, and then start a new editor process. `:PlugClean` should find the directory where the plugin was installed and delete that directory.

vim-plug does not support an uninstall command to uninstall the plugin in runtime because Vim/Neovim do not support plugin namespaces such that plugin code is isolated from the global Vim/Neovim environment and other plugins. It's useful to have one to cleanup non-Vimscript dependencies (ie. python, ruby, nodejs, binaries) because it may rely on the runtime environment.

**Comment by vaklinzi** [comment]
@janlazo I tried what you suggested but it doesn' work. I deleted the line with the Plugin, sourced the init.vim, closed the editor, opened it again and run :PlugClean and I receive the message "Already clean" but the folder of the deleted plugin is still there.

**Comment by janlazo** [comment]
Can you provide a minimal init.vim that demostrates the problem?
